### ISSUE TITLE
pytest-xdist gets crashed with `AssertionError`

### ISSUE THREAD

**Issue by suds-sky** [pytest-dev/pytest-xdist#1078]
Hi, 

I tried to add `pytest-xdist` with the current and getting the following error in the console. I am not not able to figure what is the issue. I tried with multiple versions of `pytest-xdist` but no luck. Has anyone got similar issue and know how to fix it?

```shell
Test session starts (platform: darwin, Python 3.12.3, pytest 7.4.4, pytest-sugar 0.9.7)
rootdir: /Users/abc/PycharmProjects/core-app/component-tests
configfile: pytest.ini
plugins: repeat-0.9.3, html-4.1.1, metadata-3.0.0, sugar-0.9.7, split-0.8.2, lazy-fixture-0.6.3, xdist-3.6.1
2 workers [2 items]
scheduling tests via LoadScheduling
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/abc/Library/Caches/pypoetry/virtualenvs/component-tests-O8IGgX5--py3.12/lib/python3.12/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/abc/Library/Caches/pypoetry/virtualenvs/component-tests-O8IGgX5--py3.12/lib/python3.12/site-packages/_pytest/main.py", line 325, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/abc/Library/Caches/pypoetry/virtualenvs/component-tests-O8IGgX5--py3.12/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/abc/Library/Caches/pypoetry/virtualenvs/component-tests-O8IGgX5--py3.12/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/abc/Library/Caches/pypoetry/virtualenvs/component-tests-O8IGgX5--py3.12/lib/python3.12/site-packages/pluggy/_callers.py", line 182, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/abc/Library/Caches/pypoetry/virtualenvs/component-tests-O8IGgX5--py3.12/lib/python3.12/site-packages/pluggy/_result.py", line 100, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/Users/abc/Library/Caches/pypoetry/virtualenvs/component-tests-O8IGgX5--py3.12/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/abc/Library/Caches/pypoetry/virtualenvs/component-tests-O8IGgX5--py3.12/lib/python3.12/site-packages/xdist/dsession.py", line 138, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/Users/abc/Library/Caches/pypoetry/virtualenvs/component-tests-O8IGgX5--py3.12/lib/python3.12/site-packages/xdist/dsession.py", line 163, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/Users/abc/Library/Caches/pypoetry/virtualenvs/component-tests-O8IGgX5--py3.12/lib/python3.12/site-packages/xdist/dsession.py", line 217, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('tests/parallel/test_self_install_journey.py::test_self_install_journey[device:1--]', <WorkerController gw0>)
INTERNALERROR> assert not 'tests/parallel/test_self_install_journey.py::test_self_install_journey[device:2--]'
```

**Comment by bluetech** [comment]
> I tried with multiple versions of pytest-xdist but no luck

So it happens also with pytest-xdist 3.5.0?

**Comment by suds-sky** [comment]
> > I tried with multiple versions of pytest-xdist but no luck
> 
> So it happens also with pytest-xdist 3.5.0?

Thanks for your reply. It does.

Do you know, Is there a way to debug this issue by enabling logs for pytest-xdist to see why it is getting crashed?

**Comment by suds-sky** [comment]
Managed to access the worker logs after spending long time to find out crash reason. Fixed the issues and closing this ticket now.

**Comment by lupanlpb** [comment]
> Managed to access the worker logs after spending long time to find out crash reason. Fixed the issues and closing this ticket now.

Hi, could you please point out the cause of this issue?
