### ISSUE TITLE
execnet.gateway_base.DumpError: can't serialize <class '_pytest.outcomes.XFailed'> when hasattr(call, "excinfo") and pytest.xfail() used

### ISSUE THREAD

**Issue by Mmajonez** [pytest-dev/pytest-xdist#1145]
Hi,
I'm trying to get a reason for skipped/xfailed test from inside of test body
```
@pytest.mark.xdist_group(name=PurePath(__file__).parent.name)
def test_get_crypto_address():
    check_pp_availability()
    check_ca_availability()
```
where check_pp_availability() and check_ca_availability() xfail/skip tests when a flag is set to False (dynamically, so I can't set it as a parameter)
```
def check_pp_availability():
    if not is_pp_available():
        pytest.xfail("PP not available")
```

When trying to get the reason for xfail via call.excinfo, Internal Error occurs due to `execnet.gateway_base.DumpError: can't serialize <class '_pytest.outcomes.XFailed'>`
in conftest.py:
```
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    global reason_why_marked
    outcome = yield
    report = outcome.get_result()
    match call.when:
        case "call":
            if hasattr(report, "wasxfail") and not item.get_closest_marker("xfail"):
                reason_why_marked = get_reason(call)
        case "teardown":
            report.package = get_package(item)
            report.name = str(item.function.__name__)
            report.author = get_author(item)
            report.additional = reason_why_marked or get_mark_reason(item)
            report.xdist_group = get_xdist_group(item)


def get_reason(call):
    if call.when == "call":
        if hasattr(call, "excinfo"):
            return call.excinfo.value
    return None
```

The problem occurs only if xdist is used otherwise tests are run successfully and the reason is added to a report
Similar error was present in #487

**Comment by RonnyPfannschmidt** [comment]
neither a traceback, package versions nor comprehensible code was provided, as such this isn't acionale

**Comment by Mmajonez** [comment]
pytest-xdist version 3.6.1

```
INTERNALERROR> def worker_internal_error(
INTERNALERROR>         self, node: WorkerController, formatted_error: str
INTERNALERROR>     ) -> None:
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>     
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
INTERNALERROR> E           AssertionError: Traceback (most recent call last):
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
INTERNALERROR> E                                      ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\main.py", line 337, in _main
INTERNALERROR> E                 config.hook.pytest_runtestloop(session=session)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
INTERNALERROR> E                 raise exception.with_traceback(exception.__traceback__)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
INTERNALERROR> E                 teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR> E                 ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\logging.py", line 803, in pytest_runtestloop
INTERNALERROR> E                 return (yield)  # Run all the tests.
INTERNALERROR> E                         ^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
INTERNALERROR> E                 teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR> E                 ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\terminal.py", line 673, in pytest_runtestloop
INTERNALERROR> E                 result = yield
INTERNALERROR> E                          ^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E                       ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\xdist\remote.py", line 174, in pytest_runtestloop
INTERNALERROR> E                 self.run_one_test()
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\xdist\remote.py", line 195, in run_one_test
INTERNALERROR> E                 self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 182, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_result.py", line 100, in get_result
INTERNALERROR> E                 raise exc.with_traceback(exc.__traceback__)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 167, in _multicall
INTERNALERROR> E                 teardown.throw(outcome._exception)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\warnings.py", line 112, in pytest_runtest_protocol
INTERNALERROR> E                 return (yield)
INTERNALERROR> E                         ^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 167, in _multicall
INTERNALERROR> E                 teardown.throw(outcome._exception)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\assertion\__init__.py", line 176, in pytest_runtest_protocol
INTERNALERROR> E                 return (yield)
INTERNALERROR> E                         ^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 167, in _multicall
INTERNALERROR> E                 teardown.throw(outcome._exception)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\unittest.py", line 429, in pytest_runtest_protocol
INTERNALERROR> E                 res = yield
INTERNALERROR> E                       ^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 167, in _multicall
INTERNALERROR> E                 teardown.throw(outcome._exception)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\faulthandler.py", line 88, in pytest_runtest_protocol
INTERNALERROR> E                 return (yield)
INTERNALERROR> E                         ^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E                       ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\runner.py", line 113, in pytest_runtest_protocol
INTERNALERROR> E                 runtestprotocol(item, nextitem=nextitem)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\runner.py", line 137, in runtestprotocol
INTERNALERROR> E                 reports.append(call_and_report(item, "teardown", log, nextitem=nextitem))
INTERNALERROR> E                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\_pytest\runner.py", line 246, in call_and_report
INTERNALERROR> E                 ihook.pytest_runtest_logreport(report=report)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
INTERNALERROR> E                 return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
INTERNALERROR> E                 raise exception.with_traceback(exception.__traceback__)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E                       ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\xdist\remote.py", line 255, in pytest_runtest_logreport
INTERNALERROR> E                 self.sendevent("testreport", data=data)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\xdist\remote.py", line 98, in sendevent
INTERNALERROR> E                 self.channel.send((name, kwargs))
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 912, in send
INTERNALERROR> E                 self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
INTERNALERROR> E                                                                   ^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1629, in dumps_internal
INTERNALERROR> E                 return _Serializer().save(obj)  # type: ignore[return-value]
INTERNALERROR> E                        ^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1647, in save
INTERNALERROR> E                 self._save(obj)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1667, in _save
INTERNALERROR> E                 dispatch(self, obj)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1744, in save_tuple
INTERNALERROR> E                 self._save(item)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1667, in _save
INTERNALERROR> E                 dispatch(self, obj)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1740, in save_dict
INTERNALERROR> E                 self._write_setitem(key, value)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1734, in _write_setitem
INTERNALERROR> E                 self._save(value)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1667, in _save
INTERNALERROR> E                 dispatch(self, obj)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1740, in save_dict
INTERNALERROR> E                 self._write_setitem(key, value)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1734, in _write_setitem
INTERNALERROR> E                 self._save(value)
INTERNALERROR> E               File "C:\Python312\Lib\site-packages\execnet\gateway_base.py", line 1665, in _save
INTERNALERROR> E                 raise DumpError(f"can't serialize {tp}") from None
INTERNALERROR> E             execnet.gateway_base.DumpError: can't serialize <class '_pytest.outcomes.XFailed'>
INTERNALERROR> E           assert False
INTERNALERROR> 
INTERNALERROR> C:\Python312\Lib\site-packages\xdist\dsession.py:232: AssertionError
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Python312\Lib\site-packages\_pytest\main.py", line 283, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python312\Lib\site-packages\_pytest\main.py", line 337, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "C:\Python312\Lib\site-packages\pluggy\_hooks.py", line 513, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python312\Lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 139, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python312\Lib\site-packages\_pytest\logging.py", line 803, in pytest_runtestloop
INTERNALERROR>     return (yield)  # Run all the tests.
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 122, in _multicall
INTERNALERROR>     teardown.throw(exception)  # type: ignore[union-attr]
INTERNALERROR>     ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python312\Lib\site-packages\_pytest\terminal.py", line 673, in pytest_runtestloop
INTERNALERROR>     result = yield
INTERNALERROR>              ^^^^^
INTERNALERROR>   File "C:\Python312\Lib\site-packages\pluggy\_callers.py", line 103, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "C:\Python312\Lib\site-packages\xdist\dsession.py", line 138, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "C:\Python312\Lib\site-packages\xdist\dsession.py", line 163, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "C:\Python312\Lib\site-packages\xdist\dsession.py", line 217, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('trading_account/test_crypto_address.py::test_get_crypto_address@trading_account', <WorkerController gw0>)

```

**Comment by RonnyPfannschmidt** [comment]
Putting plain exeption objects into the report is not supported 

Either use the exception info or something execnet can serialize

**Comment by Mmajonez** [comment]
Thanks, as it was shown correctly when run without xdist, I didn't even notice that it's not a string - str(call.excinfo.value) works perfectly :D
