### ISSUE TITLE
xdist fails on Python 3.6

### ISSUE THREAD

**Issue by thedrow** [pytest-dev/pytest-xdist#127]
I'm getting a strange exception when running pytest with xdist.
```
GLOB sdist-make: /home/omer/Documents/Projects/drifter/drifter-collector/setup.py
py36 create: /home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36
py36 installdeps: pytest, pytest-sugar, pytest-describe, pytest-faker, pytest-xdist, freezegun
py36 inst: /home/omer/Documents/Projects/drifter/drifter-collector/.tox/dist/drifter-collector-0.1.0.zip
py36 installed: apipkg==1.4,appdirs==1.4.2,brotlipy==0.6.0,cffi==1.9.1,drifter-collector==0.1.0,enum34==1.1.6,execnet==1.4.1,Faker==0.7.9,falcon==1.0.0,freezegun==0.3.8,gql==0.1.0,graphql-core==1.0.1,grpcio==1.1.3,hug==2.2.0,msgpack-python==0.4.8,packaging==16.8,promise==1.0.1,protobuf==3.2.0,py==1.4.32,pycparser==2.17,pypachy==0.0.2,pyparsing==2.1.10,pytest==3.0.6,pytest-describe==0.11.0,pytest-faker==2.0.0,pytest-sugar==0.8.0,pytest-xdist==1.15.0,python-dateutil==2.6.0,python-mimeparse==1.6.0,requests==2.13.0,six==1.10.0,termcolor==1.1.0,typing==3.5.3.0,xxhash==1.0.0
py36 runtests: PYTHONHASHSEED='4263827372'
py36 runtests: commands[0] | pytest --lf -n auto
Test session starts (platform: linux, Python 3.6.0, pytest 3.0.6, pytest-sugar 0.8.0)
run-last-failure: rerun last 3 failures
rootdir: /home/omer/Documents/Projects/drifter/drifter-collector, inifile: 
plugins: xdist-1.15.0, sugar-0.8.0, faker-2.0.0, describe-0.11.0
gw0 I / gw1 I / gw2 I / gw3 ITraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 3, in <module>
  File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/execnet/gateway_base.py", line 18, in <module>
    import traceback
  File "/home/omer/.pyenv/versions/3.6.0/lib/python3.6/traceback.py", line 5, in <module>
    import linecache
  File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/linecache.py", line 11, in <module>
    import tokenize
  File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/tokenize.py", line 33, in <module>
    import re
  File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/_pytest/main.py", line 96, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/xdist/dsession.py", line 509, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/xdist/slavemanage.py", line 48, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/xdist/slavemanage.py", line 52, in setup_node
INTERNALERROR>     gw = self.group.makegateway(spec)
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/execnet/multi.py", line 128, in makegateway
INTERNALERROR>     gw = gateway_bootstrap.bootstrap(io, spec)
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/execnet/gateway_bootstrap.py", line 92, in bootstrap
INTERNALERROR>     bootstrap_import(io, spec)
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/execnet/gateway_bootstrap.py", line 27, in bootstrap_import
INTERNALERROR>     s = io.read(1)
INTERNALERROR>   File "/home/omer/Documents/Projects/drifter/drifter-collector/.tox/py36/lib/python3.6/site-packages/execnet/gateway_base.py", line 389, in read
INTERNALERROR>     "expected %d bytes, got %d" % (numbytes, len(buf)))
INTERNALERROR> EOFError: expected 1 bytes, got 0
```

The enum module is importable and IntFlag is available in that module so I'm not sure what went wrong.

**Comment by thedrow** [comment]
It turns out we don't run the xdist test suite with Python 3.6 yet. See #128 for a potential solution.
We currently have two failing tests.
```
tox -e py36-pytest30
GLOB sdist-make: /home/omer/Documents/Projects/pytest-xdist/setup.py
py36-pytest30 create: /home/omer/Documents/Projects/pytest-xdist/.tox/py36-pytest30
py36-pytest30 installdeps: pycmd, setuptools_scm, pytest~=3.0.5
py36-pytest30 inst: /home/omer/Documents/Projects/pytest-xdist/.tox/dist/pytest-xdist-1.15.1.dev34+ng0f6ba88.d20170301.zip
py36-pytest30 installed: apipkg==1.4,appdirs==1.4.2,execnet==1.4.1,packaging==16.8,py==1.4.32,pycmd==1.2,pyparsing==2.1.10,pytest==3.0.6,pytest-xdist==1.15.1.dev34+ng0f6ba88.d20170301,setuptools-scm==1.15.0,six==1.10.0
py36-pytest30 runtests: PYTHONHASHSEED='3374278974'
py36-pytest30 runtests: commands[0] | py.cleanup -aq
cleaning path /home/omer/Documents/Projects/pytest-xdist/testing of extensions ['.pyc', '$py.class', 'pip-log.txt']
py36-pytest30 runtests: commands[1] | py.test
============================================================= test session starts =============================================================
platform linux -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/omer/Documents/Projects/pytest-xdist, inifile: tox.ini
plugins: xdist-1.15.1.dev34+ng0f6ba88.d20170301
collected 110 items 

acceptance_test.py ..F..F........s.x...xx.............X......
test_boxed.py ..xx..
test_dsession.py ........x..x
test_looponfail.py .............ss
test_newhooks.py ..
test_plugin.py ........
test_remote.py x.....s..x.
test_slavemanage.py ........x....s
=========================================================== short test summary info ===========================================================
SKIP [3] /home/omer/Documents/Projects/pytest-xdist/.tox/py36-pytest30/lib/python3.6/site-packages/_pytest/pytester.py:1012: could not import 'pexpect'
SKIP [1] testing/test_remote.py:185: skip at module level illegal in pytest 3.0
SKIP [1] /home/omer/Documents/Projects/pytest-xdist/.tox/py36-pytest30/lib/python3.6/site-packages/_pytest/config.py:1193: no 'gspecs' option found
FAIL acceptance_test.py::TestDistribution::()::test_n1_import_error
FAIL acceptance_test.py::TestDistribution::()::test_manytests_to_one_import_error
XFAIL acceptance_test.py::TestDistEach::()::test_simple_diffoutput
reason: [NOTRUN] other python versions might not have py.test installed
XFAIL acceptance_test.py::test_terminate_on_hangingnode
XFAIL acceptance_test.py::test_session_hooks
reason: [NOTRUN] works if run outside test suite
XFAIL test_boxed.py::test_functional_boxed_capturing[sys]
capture cleanup needed
XFAIL test_boxed.py::test_functional_boxed_capturing[fd]
capture cleanup needed
XFAIL test_dsession.py::TestDistReporter::()::test_rsync_printing
XFAIL test_dsession.py::test_pytest_issue419
duplicate test ids not supported yet
XFAIL test_remote.py::test_remoteinitconfig
#59
XFAIL test_remote.py::TestSlaveInteractor::()::test_happy_run_events_converted
reason: implement a simple test for event production
XFAIL test_slavemanage.py::TestNodeManager::()::test_rsync_roots_no_roots
reason: [NOTRUN] 
XPASS acceptance_test.py::TestNodeFailure::()::test_each_multiple #20: xdist race condition on node restart

================================================================== FAILURES ===================================================================
____________________________________________________ TestDistribution.test_n1_import_error ____________________________________________________

self = <acceptance_test.TestDistribution object at 0x7f59d2372f60>
testdir = <Testdir local('/tmp/pytest-of-omer/pytest-6/testdir/test_n1_import_error0')>

def test_n1_import_error(self, testdir):
p1 = testdir.makepyfile("""
import __import_of_missing_module
def test_import():
pass
""")
result = testdir.runpytest(p1, "-n1")
assert result.ret == 1
result.stdout.fnmatch_lines([
> "E ImportError: *__import_of_missing_module*",
])
E Failed: nomatch: 'E ImportError: *__import_of_missing_module*'
E and: '============================= test session starts =============================='
E and: 'platform linux -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0'
E and: 'rootdir: /tmp/pytest-of-omer/pytest-6/testdir/test_n1_import_error0, inifile: '
E and: 'plugins: xdist-1.15.1.dev34+ng0f6ba88.d20170301'
E and: 'gw0 I'
E and: 'gw0 [0]'
E and: ''
E and: 'scheduling tests via LoadScheduling'
E and: ''
E and: '==================================== ERRORS ===================================='
E and: '___________________ ERROR collecting test_n1_import_error.py ___________________'
E and: "ImportError while importing test module '/tmp/pytest-of-omer/pytest-6/testdir/test_n1_import_error0/test_n1_import_error.py'."
E and: 'Hint: make sure your test modules/packages have valid Python names.'
E and: 'Traceback:'
E and: 'test_n1_import_error.py:1: in <module>'
E and: ' import __import_of_missing_module'
E and: "E ModuleNotFoundError: No module named '__import_of_missing_module'"
E and: '=========================== 1 error in 0.60 seconds ============================'
E and: ''
E remains unmatched: 'E ImportError: *__import_of_missing_module*'

/home/omer/Documents/Projects/pytest-xdist/testing/acceptance_test.py:33: Failed
------------------------------------------------------------ Captured stdout call -------------------------------------------------------------
============================= test session starts ==============================
platform linux -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /tmp/pytest-of-omer/pytest-6/testdir/test_n1_import_error0, inifile: 
plugins: xdist-1.15.1.dev34+ng0f6ba88.d20170301
gw0 I
gw0 [0]

scheduling tests via LoadScheduling

==================================== ERRORS ====================================
___________________ ERROR collecting test_n1_import_error.py ___________________
ImportError while importing test module '/tmp/pytest-of-omer/pytest-6/testdir/test_n1_import_error0/test_n1_import_error.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_n1_import_error.py:1: in <module>
import __import_of_missing_module
E ModuleNotFoundError: No module named '__import_of_missing_module'
=========================== 1 error in 0.60 seconds ============================
_____________________________________________ TestDistribution.test_manytests_to_one_import_error _____________________________________________

self = <acceptance_test.TestDistribution object at 0x7f59d24043c8>
testdir = <Testdir local('/tmp/pytest-of-omer/pytest-6/testdir/test_manytests_to_one_import_error0')>

def test_manytests_to_one_import_error(self, testdir):
p1 = testdir.makepyfile("""
import __import_of_missing_module
def test_import():
pass
""")
result = testdir.runpytest(p1, '--tx=popen', '--tx=popen')
assert result.ret in (1, 2)
result.stdout.fnmatch_lines([
> "E ImportError: *__import_of_missing_module*",
])
E Failed: nomatch: 'E ImportError: *__import_of_missing_module*'
E and: '============================= test session starts =============================='
E and: 'platform linux -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0'
E and: 'rootdir: /tmp/pytest-of-omer/pytest-6/testdir/test_manytests_to_one_import_error0, inifile: '
E and: 'plugins: xdist-1.15.1.dev34+ng0f6ba88.d20170301'
E and: 'collected 0 items / 1 errors'
E and: ''
E and: '==================================== ERRORS ===================================='
E and: '____________ ERROR collecting test_manytests_to_one_import_error.py ____________'
E and: "ImportError while importing test module '/tmp/pytest-of-omer/pytest-6/testdir/test_manytests_to_one_import_error0/test_manytests_to_one_import_error.py'."
E and: 'Hint: make sure your test modules/packages have valid Python names.'
E and: 'Traceback:'
E and: 'test_manytests_to_one_import_error.py:1: in <module>'
E and: ' import __import_of_missing_module'
E and: "E ModuleNotFoundError: No module named '__import_of_missing_module'"
E and: '!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!'
E and: '=========================== 1 error in 0.22 seconds ============================'
E and: ''
E remains unmatched: 'E ImportError: *__import_of_missing_module*'

/home/omer/Documents/Projects/pytest-xdist/testing/acceptance_test.py:67: Failed
------------------------------------------------------------ Captured stdout call -------------------------------------------------------------
============================= test session starts ==============================
platform linux -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /tmp/pytest-of-omer/pytest-6/testdir/test_manytests_to_one_import_error0, inifile: 
plugins: xdist-1.15.1.dev34+ng0f6ba88.d20170301
collected 0 items / 1 errors

==================================== ERRORS ====================================
____________ ERROR collecting test_manytests_to_one_import_error.py ____________
ImportError while importing test module '/tmp/pytest-of-omer/pytest-6/testdir/test_manytests_to_one_import_error0/test_manytests_to_one_import_error.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_manytests_to_one_import_error.py:1: in <module>
import __import_of_missing_module
E ModuleNotFoundError: No module named '__import_of_missing_module'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.22 seconds ============================
=================================== 2 failed, 92 passed, 5 skipped, 10 xfailed, 1 xpassed in 60.39 seconds ====================================
ERROR: InvocationError: '/home/omer/Documents/Projects/pytest-xdist/.tox/py36-pytest30/bin/py.test'
___________________________________________________________________ summary ___________________________________________________________________
ERROR: py36-pytest30: commands failed
```.

**Comment by bradmwalker** [comment]
Uninstalling the enum34 package may fix pytest-xdist runs, but it might break other processes using dependencies that specifically reference enum34. grpc/grpc#9900

**Comment by RonnyPfannschmidt** [comment]
enum34 is broken on python >= 3.4, i propose we split the issue about python 3.6 out and close the rest as invalid, enum34 should never be installed on later python versions

**Comment by LorcanHamill** [comment]
I saw this same problem when building pytest-xdist with Python 3.6.  It seems that the tests are expecting to get ImportError in circumstances that now result in ModuleNotFoundError.   The tests use fnmatch() with strings like this:

           "E   ImportError: *__import_of_missing_module*",

they can be made to pass by making those strings more generic like this:

            "E   *Error: *__import_of_missing_module*",

That's pretty generic, though.  They also seem to work when I add "No module named", which makes the tests a bit tighter:

            "E   *Error: No module named *__import_of_missing_module*",

(The remaining around the module name are still needed, I think, because different versions of Python do and don't put the module name in quotes.)

Hope this helps.

**Comment by nicoddemus** [comment]
@LorcanHamill thanks!

**Comment by pelme** [comment]
I ran into the same issue and had enum34 installed in my Python 3.6 virtualenv without realizing it. When getting rid of enum34, this error disappeared and pytest-xdist works again.

Closing this issue since Python 3.6 test runs are in master with passing tests!

**Comment by davidemoro** [comment]
Hi,

I have the same issue with the following setup:
```
metadata: {'Python': '3.6.1', 'Platform': 'Linux-4.10.0-33-generic-x86_64-with-Ubuntu-17.04-zesty', 'Packages': {'pytest': '3.2.1', 'py': '1.4.34', 'pluggy': '0.4.0'}, 'Plugins': {'xdist': '1.20.0', 'variables': '1.7.0', 'travis-fold': '1.2.0', 'testrail': '0.0.11', 'splinter': '1.8.1', 'pypom-navigation': '0.0.1', 'metadata': '1.3.0', 'html': '1.14.2', 'forked': '0.2', 'cov': '2.4.0', 'bdd': '2.18.1'}}
rootdir: /home/davide/workspaces/pcm2_qa, inifile: setup.cfg
plugins: xdist-1.20.0, variables-1.7.0, travis-fold-1.2.0, testrail-0.0.11, splinter-1.8.1, pypom-navigation-0.0.1, metadata-1.3.0, html-1.14.2, forked-0.2, cov-2.4.0, bdd-2.18.1
```

What are the known good versions for make it works running with python 3.6?

Thanks in advance,

davide

**Comment by pelme** [comment]
@davidemoro make sure you **do not** have enum34 installed. That was the issue for me.

**Comment by nicoddemus** [comment]
@davidemoro if you don't have `enum34` installed please open a new issue.

**Comment by davidemoro** [comment]
Hi @pelme, @nicoddemus,

all works fine removing enum34, thanks!
