### ISSUE TITLE
pip install fails with missing six module - probably bug in setuptools

### ISSUE THREAD

**Issue by matthew-brett** [pytest-dev/pytest-xdist#151]
Summary - something in setuptools just broke your install.

Either of:

* `pip install git+https://github.com/pytest-dev/pytest-xdist`
* `pip install pytest-xdist`

fails with (example):

```
$ pip install git+https://github.com/pytest-dev/pytest-xdist
Collecting git+https://github.com/pytest-dev/pytest-xdist
  Cloning https://github.com/pytest-dev/pytest-xdist to /private/var/folders/s7/r25pn2xj48n4cm76_mgsb78h0000gn/T/pip-3t6Ui1-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s7/r25pn2xj48n4cm76_mgsb78h0000gn/T/pip-3t6Ui1-build/setup.py", line 37, in <module>
        'Programming Language :: Python :: 3',
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/mb312/.virtualenvs/test/lib/python2.7/site-packages/setuptools/dist.py", line 320, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/Users/mb312/.virtualenvs/test/lib/python2.7/site-packages/setuptools/dist.py", line 377, in fetch_build_eggs
        replace_conflicting=True,
      File "/Users/mb312/.virtualenvs/test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 852, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/mb312/.virtualenvs/test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1124, in best_match
        return self.obtain(req, installer)
      File "/Users/mb312/.virtualenvs/test/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1136, in obtain
        return installer(requirement)
      File "/Users/mb312/.virtualenvs/test/lib/python2.7/site-packages/setuptools/dist.py", line 421, in fetch_build_egg
        from setuptools.command.easy_install import easy_install
      File "/Users/mb312/.virtualenvs/test/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 49, in <module>
        from setuptools.py27compat import rmtree_safe
      File "/Users/mb312/.virtualenvs/test/lib/python2.7/site-packages/setuptools/py27compat.py", line 7, in <module>
        import six
    ImportError: No module named six
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/s7/r25pn2xj48n4cm76_mgsb78h0000gn/T/pip-3t6Ui1-build/
```

Installing 1.15.0 works fine, and downgrading to setuptools 35.0.2 also works.  Setuptools 36.0.0 was released today. So I suspect you've uncovered a new bug in setuptools - just to let you know :(

**Comment by RonnyPfannschmidt** [comment]
pypa/setuptools#1043 will fix this
