### ISSUE TITLE
Regression in pip test suite

### ISSUE THREAD

**Issue by xavfernandez** [pytest-dev/pytest-xdist#160]
We went from https://travis-ci.org/pypa/pip/jobs/241184675#L218 to https://travis-ci.org/pypa/pip/jobs/241509953#L218 and the only thing that changed was pytest-xdist going from 1.16.0 to 1.17.0.

<details>

```
+tox -- -m integration -n 8 --duration=5
[1mGLOB sdist-make: /home/travis/build/pypa/pip/setup.py[0m
[1mpy34 inst-nodeps: /home/travis/build/pypa/pip/.tox/dist/pip-10.0.0.dev0.zip[0m
[1mpy34 installed: apipkg==1.4,execnet==1.4.1,freezegun==0.3.9,mock==1.0.1,pretend==1.0.8,py==1.4.34,pytest==3.1.2,pytest-catchlog==1.2.2,pytest-rerunfailures==2.1.0,pytest-timeout==1.2.0,pytest-xdist==1.17.0,python-dateutil==2.6.0,scripttest==1.3,six==1.10.0,virtualenv==15.2.0.dev0[0m
[1mpy34 runtests: PYTHONHASHSEED='472861946'[0m
[1mpy34 runtests: commands[0] | py.test --timeout 300 -m integration -n 8 --duration=5[0m
[1m============================= test session starts ==============================[0m
platform linux -- Python 3.4.4, pytest-3.1.2, py-1.4.34, pluggy-0.4.0
rootdir: /home/travis/build/pypa/pip, inifile: setup.cfg
plugins: xdist-1.17.0, timeout-1.2.0, rerunfailures-2.1.0, catchlog-1.2.2
timeout: 300.0s method: signal
[1m
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I[0m[1m
gw0 C / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I[0m[1m
gw0 C / gw1 C / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I[0m[1m
gw0 C / gw1 C / gw2 C / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I[0m[1m
gw0 C / gw1 C / gw2 C / gw3 C / gw4 I / gw5 I / gw6 I / gw7 I[0m[1m
gw0 C / gw1 C / gw2 C / gw3 C / gw4 C / gw5 I / gw6 I / gw7 I[0m[1m
gw0 C / gw1 C / gw2 C / gw3 C / gw4 C / gw5 C / gw6 I / gw7 I[0m[1m
gw0 C / gw1 C / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 I[0m[1m
gw0 C / gw1 C / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 C[0m[1m
gw0 ok / gw1 C / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 C[0m[1m
gw0 ok / gw1 ok / gw2 C / gw3 C / gw4 C / gw5 C / gw6 C / gw7 C[0m[1m
gw0 ok / gw1 ok / gw2 ok / gw3 C / gw4 C / gw5 C / gw6 C / gw7 C[0m[1m
gw0 ok / gw1 ok / gw2 ok / gw3 ok / gw4 C / gw5 C / gw6 C / gw7 C[0m[1m
gw0 ok / gw1 ok / gw2 ok / gw3 ok / gw4 ok / gw5 C / gw6 C / gw7 C[0m[1m
gw0 ok / gw1 ok / gw2 ok / gw3 ok / gw4 ok / gw5 ok / gw6 C / gw7 C[0m[1m
gw0 ok / gw1 ok / gw2 ok / gw3 ok / gw4 ok / gw5 ok / gw6 ok / gw7 C[0m[1m
gw0 ok / gw1 ok / gw2 ok / gw3 ok / gw4 ok / gw5 ok / gw6 ok / gw7 ok[0m[1m
gw0 [359] / gw1 ok / gw2 ok / gw3 ok / gw4 ok / gw5 ok / gw6 ok / gw7 ok[0m[1m
gw0 [359] / gw1 [359] / gw2 ok / gw3 ok / gw4 ok / gw5 ok / gw6 ok / gw7 ok[0m[1m
gw0 [359] / gw1 [359] / gw2 [359] / gw3 ok / gw4 ok / gw5 ok / gw6 ok / gw7 ok[0m[1m
gw0 [359] / gw1 [359] / gw2 [359] / gw3 [359] / gw4 ok / gw5 ok / gw6 ok / gw7 ok[0m[1m
gw0 [359] / gw1 [359] / gw2 [359] / gw3 [359] / gw4 [359] / gw5 ok / gw6 ok / gw7 ok[0m[1m
gw0 [359] / gw1 [359] / gw2 [359] / gw3 [359] / gw4 [359] / gw5 [359] / gw6 ok / gw7 ok[0m[1m
gw0 [359] / gw1 [359] / gw2 [359] / gw3 [359] / gw4 [359] / gw5 [359] / gw6 [359] / gw7 ok[0m[1m
gw0 [359] / gw1 [359] / gw2 [359] / gw3 [359] / gw4 [359] / gw5 [359] / gw6 [359] / gw7 [359][0m
scheduling tests via LoadScheduling
.....................................x........................sINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/travis/build/pypa/pip/.tox/py34/lib/python3.4/site-packages/_pytest/main.py", line 105, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/travis/build/pypa/pip/.tox/py34/lib/python3.4/site-packages/_pytest/main.py", line 141, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/travis/build/pypa/pip/.tox/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/build/pypa/pip/.tox/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/travis/build/pypa/pip/.tox/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/travis/build/pypa/pip/.tox/py34/lib/python3.4/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/travis/build/pypa/pip/.tox/py34/lib/python3.4/site-packages/xdist/dsession.py", line 539, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/travis/build/pypa/pip/.tox/py34/lib/python3.4/site-packages/xdist/dsession.py", line 558, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/travis/build/pypa/pip/.tox/py34/lib/python3.4/site-packages/xdist/dsession.py", line 664, in slave_testreport
INTERNALERROR>     self.sched.mark_test_complete(node, rep.item_index, rep.duration)
INTERNALERROR>   File "/home/travis/build/pypa/pip/.tox/py34/lib/python3.4/site-packages/xdist/dsession.py", line 280, in mark_test_complete
INTERNALERROR>     self.node2pending[node].remove(item_index)
INTERNALERROR> ValueError: list.remove(x): x not in list
```

</details>

**Comment by nicoddemus** [comment]
Please upgrade to 1.17.1 (#157)

**Comment by nicoddemus** [comment]
(sorry for the terse response as I'm on my phone)

**Comment by xavfernandez** [comment]
My bad, I checked for open issues but not closed ones 🙇 .

**Comment by nicoddemus** [comment]
No worries! :+1:
