### ISSUE TITLE
xdist fails to import python module in conftest.py inside travis container

### ISSUE THREAD

**Issue by havok2063** [pytest-dev/pytest-xdist#184]
I have a test suite I'm trying to run using xdist parallelization inside Travis builds, and it seems to be crashing when trying to import a python package located inside my conftest.py file.  If I don't use xdist to run the tests in Travis, the tests all start and run fine.   Also, running my test suite with xdist on my local laptop works just fine.  It's only inside the Travis builds that it fails strangely.   

This particular python module (sdss_access) is a custom module that is set up and loaded into the sys path when another (also custom but main) package (marvin) is imported and set up.  So it's like an external dependency that lives inside marvin that upon import gets added into the `sys.path` so the package is importable and usable elsewhere. 

```
# all external dependencies are set up to be importable when marvin is imported 
import marvin  
marvin.__file__
 '/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/__init__.pyc'

# now importable dependency 
import sdss_access
sdss_access.__file__
'/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/extern/sdss_access/python/sdss_access/__init__.pyc'
```

Here is an example `conftest.py` 
```
import pytest
from marvin import config, marvindb
from sdss_access.path import Path

anum = [1, 2, 3, 4]
bnum = [5, 6, 7, 8]

@pytest.fixture(params=anum)
def a(request):
    return request.param

@pytest.fixture(params=bnum)
def b(request):
    return request.param
```
and example `test_stuff.py` test file that mimic the problem
```
import pytest

@pytest.mark.parametrize('exp', [(6), (8), (10), (12)])
def test_stuff(a, b, exp):
    c = a + b
    pytest.approx(c, exp)
```
Running `pytest test_stuff.py` works fine.  When I run with `pytest -n 4 test_stuff.py` I get the following error.  However, If I remove the `conftest.py` file altogether and move its content inside the `test_stuff.py` file, then `pytest -n 4 test_stuff.py` runs fine and all tests pass.  

So is there some weird issue with how pytest-xdist handles the conftest file inside multi-processes where it forgets about the Python environment that gets set up?  How does xdist split off tests into the processes?

Error traceback
```
(test_env) travis@a7428a22e8cf:~$ pytest -n 4 test_stuff.py
Test session starts (platform: linux2, Python 2.7.13, pytest 3.1.3, pytest-sugar 0.8.0)
rootdir: /home/travis, inifile:
plugins: flask-0.10.0, xdist-1.18.1, sugar-0.8.0, cov-2.5.1
gw0 C / gw1 C / gw2 C / gw3 C/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/core/exceptions.py:53: UserWarning: cannot initiate Sentry error reporting: [Errno 25] Inappropriate ioctl for device.
  UserWarning)
[gw0] node down: Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python2.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 180, in <module>
  File "<remote exec>", line 154, in remote_initconfig
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 965, in fromdictargs
    config.parse(args, addopts=False)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 1106, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 1077, in _preparse
    args=args, parser=self._parser)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 980, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 319, in _set_initial_conftests
    self._try_load_conftest(anchor)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 325, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 339, in _getconftestmodules
    clist = self._getconftestmodules(path.dirpath())
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 350, in _getconftestmodules
    mod = self._importconftest(conftestpath)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 375, in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
ConftestImportFailure: ImportError('No module named sdss_access.path',)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 211, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/travis/miniconda/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/home/travis/conftest.py", line 4, in <module>
    from sdss_access.path import Path
```

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus can you take a look, im unfamiliar with conda

**Comment by nicoddemus** [comment]
> So is there some weird issue with how pytest-xdist handles the conftest file inside multi-processes where it forgets about the Python environment that gets set up? How does xdist split off tests into the processes?

Each worker acts a separate session, collecting all tests and sending their ids to the master node, which in turn selects which tests run in each worker. Please take a look at [OVERVIEW](
https://github.com/pytest-dev/pytest-xdist/blob/master/OVERVIEW.md) for more details.

Looking at the description nothing obvious strikes me that could explain your problem. The `conftest.py` file (which is located at the root of your installation? That's unusual) is imported by each worker, so the "path" setting should work.

I suggest to print the contents of `sys.path` before attempting to import `sdss_access` in `conftest.py` to try to pinpoint the problem:

```python
import pytest
from marvin import config, marvindb
import sys
print('sys.path:')
for x in sys.path: print(x)
from sdss_access.path import Path
```

**Comment by havok2063** [comment]
Here is the output of my sys.path printed after the marvin import but before the sdss_access import.  It looks like the module is correctly included in the sys.path.   The `conftest.py` located at root is just my small test example file that mimics the real one.  The real `conftest.py` is in the package proper, `sdss/marvin/python/marvin/tests/`.  I experience the same problems with the real one.  

```
(test_env) travis@a7428a22e8cf:~$ pytest -s -v -n 4 test_stuff.py
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/core/exceptions.py:53: UserWarning: cannot initiate Sentry error reporting: [Errno 2] No such file or directory.
  UserWarning)
INFO: No release version set. Setting default to MPL-5
sys.path
/home/travis
/home/travis
/home/travis/miniconda/bin
/home/travis/miniconda/lib/python2.7
/home/travis/miniconda/lib/python2.7/lib-dynload
/home/travis/miniconda/lib/python2.7/lib-old
/home/travis/miniconda/lib/python2.7/lib-tk
/home/travis/miniconda/lib/python2.7/plat-linux2
/home/travis/miniconda/lib/python2.7/site-packages
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/extern/sdss_access/python
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/extern/tree/python
/home/travis/miniconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg
/home/travis/miniconda/lib/python27.zip
/home/travis/sdss/marvin/python


Test session starts (platform: linux2, Python 2.7.13, pytest 3.1.3, pytest-sugar 0.8.0)
cachedir: .cache
rootdir: /home/travis, inifile:
plugins: flask-0.10.0, xdist-1.18.1, sugar-0.8.0, cov-2.5.1
[gw0] linux2 Python 2.7.13 cwd: /home/travis
[gw1] linux2 Python 2.7.13 cwd: /home/travis
[gw2] linux2 Python 2.7.13 cwd: /home/travis
[gw3] linux2 Python 2.7.13 cwd: /home/travis
gw0 C / gw1 C / gw2 C / gw3 C/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/core/exceptions.py:53: UserWarning: cannot initiate Sentry error reporting: [Errno 25] Inappropriate ioctl for device.
  UserWarning)
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/core/exceptions.py:53: UserWarning: cannot initiate Sentry error reporting: [Errno 25] Inappropriate ioctl for device.
  UserWarning)
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/core/exceptions.py:53: UserWarning: cannot initiate Sentry error reporting: [Errno 25] Inappropriate ioctl for device.
  UserWarning)
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/core/exceptions.py:53: UserWarning: cannot initiate Sentry error reporting: [Errno 25] Inappropriate ioctl for device.
  UserWarning)
[gw0] node down: Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python2.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 180, in <module>
  File "<remote exec>", line 154, in remote_initconfig
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 965, in fromdictargs
    config.parse(args, addopts=False)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 1106, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 1077, in _preparse
    args=args, parser=self._parser)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 980, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 319, in _set_initial_conftests
    self._try_load_conftest(anchor)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 325, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 339, in _getconftestmodules
    clist = self._getconftestmodules(path.dirpath())
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 350, in _getconftestmodules
    mod = self._importconftest(conftestpath)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 375, in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
ConftestImportFailure: ImportError('No module named sdss_access.path',)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 211, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/travis/miniconda/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/home/travis/conftest.py", line 13, in <module>
    from sdss_access.path import Path


Replacing crashed slave gw0
[gw4] linux2 Python 2.7.13 cwd: /home/travis
gw4 C / gw1 C / gw2 C / gw3 C[gw2] node down: Traceback (most recent call last):
  File "/home/travis/miniconda/lib/python2.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 180, in <module>
  File "<remote exec>", line 154, in remote_initconfig
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 965, in fromdictargs
    config.parse(args, addopts=False)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 1106, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 1077, in _preparse
    args=args, parser=self._parser)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 254, in _wrapped_call
    return call_outcome.get_result()
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
    _reraise(*ex)  # noqa
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
    self.result = func()
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 980, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(early_config.known_args_namespace)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 319, in _set_initial_conftests
    self._try_load_conftest(anchor)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 325, in _try_load_conftest
    self._getconftestmodules(anchor)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 339, in _getconftestmodules
    clist = self._getconftestmodules(path.dirpath())
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 350, in _getconftestmodules
    mod = self._importconftest(conftestpath)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/config.py", line 375, in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
ConftestImportFailure: ImportError('No module named sdss_access.path',)
  File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 211, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/travis/miniconda/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
    exec2(obj, globals, locals)
  File "<string>", line 7, in exec2
  File "/home/travis/conftest.py", line 13, in <module>
    from sdss_access.path import Path
```

Here is the output of the path when it runs correctly, without xdist

```
(test_env) travis@a7428a22e8cf:~$ pytest -s -v test_stuff.py
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/core/exceptions.py:53: UserWarning: cannot initiate Sentry error reporting: [Errno 2] No such file or directory.
  UserWarning)
INFO: No release version set. Setting default to MPL-5
sys.path
/home/travis
/home/travis
/home/travis/miniconda/bin
/home/travis/miniconda/lib/python2.7
/home/travis/miniconda/lib/python2.7/lib-dynload
/home/travis/miniconda/lib/python2.7/lib-old
/home/travis/miniconda/lib/python2.7/lib-tk
/home/travis/miniconda/lib/python2.7/plat-linux2
/home/travis/miniconda/lib/python2.7/site-packages
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/extern/sdss_access/python
/home/travis/miniconda/lib/python2.7/site-packages/sdss_marvin-2.1.4.dev0-py2.7.egg/marvin/extern/tree/python
/home/travis/miniconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg
/home/travis/miniconda/lib/python27.zip
/home/travis/sdss/marvin/python


Test session starts (platform: linux2, Python 2.7.13, pytest 3.1.3, pytest-sugar 0.8.0)
cachedir: .cache
rootdir: /home/travis, inifile:
plugins: flask-0.10.0, xdist-1.18.1, sugar-0.8.0, cov-2.5.1

 test_stuff.py::test_stuff[1-5-6] ✓                                                                                                                                                                       2% ▎
 test_stuff.py::test_stuff[1-5-8] ✓                                                                                                                                                                       3% ▍
 test_stuff.py::test_stuff[1-5-10] ✓                                                                                                                                                                      5% ▌
 test_stuff.py::test_stuff[1-5-12] ✓                                                                                                                                                                      6% ▋
 test_stuff.py::test_stuff[1-6-6] ✓                                                                                                                                                                       8% ▊
 test_stuff.py::test_stuff[1-6-8] ✓                                                                                                                                                                       9% ▉
 test_stuff.py::test_stuff[1-6-10] ✓                                                                                                                                                                     11% █▏
 test_stuff.py::test_stuff[1-6-12] ✓                                                                                                                                                                     13% █▍
 test_stuff.py::test_stuff[1-7-6] ✓                                                                                                                                                                      14% █▌
 test_stuff.py::test_stuff[1-7-8] ✓                                                                                                                                                                      16% █▋
 test_stuff.py::test_stuff[1-7-10] ✓                                                                                                                                                                     17% █▊
 test_stuff.py::test_stuff[1-7-12] ✓                                                                                                                                                                     19% █▉
 test_stuff.py::test_stuff[1-8-6] ✓                                                                                                                                                                      20% ██
 test_stuff.py::test_stuff[1-8-8] ✓                                                                                                                                                                      22% ██▎
 test_stuff.py::test_stuff[1-8-10] ✓                                                                                                                                                                     23% ██▍
 test_stuff.py::test_stuff[1-8-12] ✓                                                                                                                                                                     25% ██▌
 test_stuff.py::test_stuff[2-5-6] ✓                                                                                                                                                                      27% ██▋
 test_stuff.py::test_stuff[2-5-8] ✓                                                                                                                                                                      28% ██▊
 test_stuff.py::test_stuff[2-5-10] ✓                                                                                                                                                                     30% ███
 test_stuff.py::test_stuff[2-5-12] ✓                                                                                                                                                                     31% ███▎
 test_stuff.py::test_stuff[2-6-6] ✓                                                                                                                                                                      33% ███▍
 test_stuff.py::test_stuff[2-6-8] ✓                                                                                                                                                                      34% ███▌
 test_stuff.py::test_stuff[2-6-10] ✓                                                                                                                                                                     36% ███▋
 test_stuff.py::test_stuff[2-6-12] ✓                                                                                                                                                                     38% ███▊
 test_stuff.py::test_stuff[2-7-6] ✓                                                                                                                                                                      39% ███▉
 test_stuff.py::test_stuff[2-7-8] ✓                                                                                                                                                                      41% ████▏
 test_stuff.py::test_stuff[2-7-10] ✓                                                                                                                                                                     42% ████▎
 test_stuff.py::test_stuff[2-7-12] ✓                                                                                                                                                                     44% ████▍
 test_stuff.py::test_stuff[2-8-6] ✓                                                                                                                                                                      45% ████▌
 test_stuff.py::test_stuff[2-8-8] ✓                                                                                                                                                                      47% ████▊
 test_stuff.py::test_stuff[2-8-10] ✓                                                                                                                                                                     48% ████▉
 test_stuff.py::test_stuff[2-8-12] ✓                                                                                                                                                                     50% █████
 test_stuff.py::test_stuff[3-5-6] ✓                                                                                                                                                                      52% █████▎
 test_stuff.py::test_stuff[3-5-8] ✓                                                                                                                                                                      53% █████▍
 test_stuff.py::test_stuff[3-5-10] ✓                                                                                                                                                                     55% █████▌
 test_stuff.py::test_stuff[3-5-12] ✓                                                                                                                                                                     56% █████▋
 test_stuff.py::test_stuff[3-6-6] ✓                                                                                                                                                                      58% █████▊
 test_stuff.py::test_stuff[3-6-8] ✓                                                                                                                                                                      59% █████▉
 test_stuff.py::test_stuff[3-6-10] ✓                                                                                                                                                                     61% ██████▏
 test_stuff.py::test_stuff[3-6-12] ✓                                                                                                                                                                     63% ██████▍
 test_stuff.py::test_stuff[3-7-6] ✓                                                                                                                                                                      64% ██████▌
 test_stuff.py::test_stuff[3-7-8] ✓                                                                                                                                                                      66% ██████▋
 test_stuff.py::test_stuff[3-7-10] ✓                                                                                                                                                                     67% ██████▊
 test_stuff.py::test_stuff[3-7-12] ✓                                                                                                                                                                     69% ██████▉
 test_stuff.py::test_stuff[3-8-6] ✓                                                                                                                                                                      70% ███████
 test_stuff.py::test_stuff[3-8-8] ✓                                                                                                                                                                      72% ███████▎
 test_stuff.py::test_stuff[3-8-10] ✓                                                                                                                                                                     73% ███████▍
 test_stuff.py::test_stuff[3-8-12] ✓                                                                                                                                                                     75% ███████▌
 test_stuff.py::test_stuff[4-5-6] ✓                                                                                                                                                                      77% ███████▋
 test_stuff.py::test_stuff[4-5-8] ✓                                                                                                                                                                      78% ███████▊
 test_stuff.py::test_stuff[4-5-10] ✓                                                                                                                                                                     80% ████████
 test_stuff.py::test_stuff[4-5-12] ✓                                                                                                                                                                     81% ████████▎
 test_stuff.py::test_stuff[4-6-6] ✓                                                                                                                                                                      83% ████████▍
 test_stuff.py::test_stuff[4-6-8] ✓                                                                                                                                                                      84% ████████▌
 test_stuff.py::test_stuff[4-6-10] ✓                                                                                                                                                                     86% ████████▋
 test_stuff.py::test_stuff[4-6-12] ✓                                                                                                                                                                     88% ████████▊
 test_stuff.py::test_stuff[4-7-6] ✓                                                                                                                                                                      89% ████████▉
 test_stuff.py::test_stuff[4-7-8] ✓                                                                                                                                                                      91% █████████▏
 test_stuff.py::test_stuff[4-7-10] ✓                                                                                                                                                                     92% █████████▎
 test_stuff.py::test_stuff[4-7-12] ✓                                                                                                                                                                     94% █████████▍
 test_stuff.py::test_stuff[4-8-6] ✓                                                                                                                                                                      95% █████████▌
 test_stuff.py::test_stuff[4-8-8] ✓                                                                                                                                                                      97% █████████▊
 test_stuff.py::test_stuff[4-8-10] ✓                                                                                                                                                                     98% █████████▉
 test_stuff.py::test_stuff[4-8-12] ✓                                                                                                                                                                    100% ██████████

Results (0.13s):
      64 passed
```

**Comment by kalidasya** [comment]
@havok2063 I know its an old issue, but I am facing something similar with xdist and docker, did u find a solution?

**Comment by ssbarnea** [comment]
Safe to close, travis is no longer using containers.

**Comment by nicoddemus** [comment]
Thanks @ssbarnea for the ping.
