### ISSUE TITLE
repeately crashing slaves on py3.6   SyntaxError

### ISSUE THREAD

**Issue by jason-neal** [pytest-dev/pytest-xdist#197]
I am trying to run `pytest-xdist` on travis-ci [here](https://travis-ci.org/DanielAndreasen/SWEETer-Cat/jobs/259690369 ) and getting a crashed slaves from a  `SyntaxError`.

A new slave is created which also fails, repeatedly. 
py27, 34, 35 all seem to work fine
The Traceback of the first failure is provided below.
```
pytest --cov=. --cov-report term-missing --durations 5 -n 2
============================= test session starts ==============================

platform linux -- Python 3.6.2, pytest-3.1.3, py-1.4.34, pluggy-0.4.0

rootdir: /home/travis/build/DanielAndreasen/SWEETer-Cat/sweetercat, inifile:
plugins: cov-2.5.1, flask-0.10.0, xdist-1.18.2
gw0 I / gw1 I

[gw0] node down: Traceback (most recent call last):
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/execnet/gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 180, in <module>
  File "<remote exec>", line 154, in remote_initconfig
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/config.py", line 965, in fromdictargs
    config.parse(args, addopts=False)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/config.py", line 1106, in parse
    self._preparse(args, addopts=addopts)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/config.py", line 1068, in _preparse
    self.pluginmanager.load_setuptools_entrypoints('pytest11')
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 510, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2258, in load
    return self.resolve()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2264, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/_pytest/assertion/rewrite.py", line 211, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/pytest_flask/plugin.py", line 11, in <module>
    from flask import json
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/flask/__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/jinja2/__init__.py", line 81, in <module>
    _patch_async()
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/jinja2/__init__.py", line 77, in _patch_async
    from jinja2.asyncsupport import patch_all
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 13, in <module>
    import asyncio
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/asyncio/base_events.py", line 17, in <module>
    import concurrent.futures
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/travis/miniconda/envs/test-environment/lib/python3.6/site-packages/concurrent/futures/_base.py", line 381
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax

Replacing crashed slave gw0

```

Then skipping the Traceback info I get 
```

[gw1] node down: Traceback (most recent call last):
...
SyntaxError: invalid syntax

Replacing crashed slave gw1

[gw3] node down: Traceback (most recent call last):
...
SyntaxError: invalid syntax

Replacing crashed slave gw3
```

**Comment by RonnyPfannschmidt** [comment]
at first glance this looks like you installed the backport of concurrent.futures into python3.6 and broke the stdlib using it
please prevent the offending package and report back (it should be in the stdlib in 3.6, not site-packages)

**Comment by jason-neal** [comment]
Thanks! That solved the problem.

**Comment by RonnyPfannschmidt** [comment]
glad to be of help
