### ISSUE TITLE
testsuite completely falls appart locally 

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-xdist#203]
```

Replacing crashed slave gw494
[gw495] node down: Traceback (most recent call last):
  File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 174, in <module>
OSError: [Errno 2] No such file or directory

Replacing crashed slave gw495
[gw496] node down: Traceback (most recent call last):
  File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 174, in <module>
OSError: [Errno 2] No such file or directory

Replacing crashed slave gw496
[gw497] node down: Traceback (most recent call last):
  File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 174, in <module>
OSError: [Errno 2] No such file or directory

Replacing crashed slave gw497
[gw498] node down: Traceback (most recent call last):
  File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/execnet/gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 174, in <module>
OSError: [Errno 2] No such file or directory

Replacing crashed slave gw498
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 110, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/_pytest/main.py", line 146, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 302, in __call__
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 280, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 265, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 300, in <lambda>
INTERNALERROR>     outcome = _CallOutcome(lambda: self.oldcall(hook, hook_impls, kwargs))
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/xdist/dsession.py", line 114, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/xdist/dsession.py", line 133, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/xdist/dsession.py", line 197, in slave_errordown
INTERNALERROR>     self._clone_node(node)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/xdist/dsession.py", line 261, in _clone_node
INTERNALERROR>     node = self.nodemanager.setup_node(spec, self.queue.put)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/xdist/slavemanage.py", line 68, in setup_node
INTERNALERROR>     gw = self.group.makegateway(spec)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/execnet/multi.py", line 127, in makegateway
INTERNALERROR>     io = gateway_io.create_io(spec, execmodel=self.execmodel)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/execnet/gateway_io.py", line 113, in create_io
INTERNALERROR>     return Popen2IOMaster(args, execmodel)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/execnet/gateway_io.py", line 17, in __init__
INTERNALERROR>     self.popen = p = execmodel.PopenPiped(args)
INTERNALERROR>   File "/home/rpfannsc/Projects/pytest-dev/pytest-xdist/.tox/py27/lib/python2.7/site-packages/execnet/gateway_base.py", line 178, in PopenPiped
INTERNALERROR>     return self.subprocess.Popen(args, stdout=PIPE, stdin=PIPE)
INTERNALERROR>   File "/usr/lib64/python2.7/subprocess.py", line 390, in __init__
INTERNALERROR>     errread, errwrite)
INTERNALERROR>   File "/usr/lib64/python2.7/subprocess.py", line 908, in _execute_child
INTERNALERROR>     errpipe_read, errpipe_write = self.pipe_cloexec()
INTERNALERROR>   File "/usr/lib64/python2.7/subprocess.py", line 860, in pipe_cloexec
INTERNALERROR>     r, w = os.pipe()
INTERNALERROR> OSError: [Errno 24] Too many open files
```

**Comment by nicoddemus** [comment]
I can't reproduce this, is still an issue for you @RonnyPfannschmidt ?

**Comment by RonnyPfannschmidt** [comment]
it happens regular, i will follow up with details as its happening sporadic

**Comment by RonnyPfannschmidt** [comment]
closing as its no longer replicating
