### ISSUE TITLE
When run with -n opt, AttributeError: 'Config' object has no attribute '_tmpdirhandler'

### ISSUE THREAD

**Issue by yoloseem** [pytest-dev/pytest-xdist#21]
```pytest
$ py.test -n auto common/tests/test_sys.py
================================================= test session starts ==================================================
platform darwin -- Python 2.7.9, pytest-2.8.3, py-1.4.31, pluggy-0.3.1
django settings: proj.settings.local (from environment variable)
rootdir: /Users/khj/works/projrepo/proj, inifile: pytest.ini
plugins: cov-2.1.0, django-2.9.1, xdist-1.13.1
gw0 C / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 IINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/_pytest/main.py", line 88, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/xdist/dsession.py", line 494, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/xdist/slavemanage.py", line 45, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/xdist/slavemanage.py", line 54, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/xdist/slavemanage.py", line 216, in setup
INTERNALERROR>     basetemp = self.config._tmpdirhandler.getbasetemp()
INTERNALERROR> AttributeError: 'Config' object has no attribute '_tmpdirhandler'
```

* Without `-n` option, runs well.

**Comment by RonnyPfannschmidt** [comment]
osx elc by chance?

**Comment by yoloseem** [comment]
@RonnyPfannschmidt  oh yes... 

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11
BuildVersion:	15A284
```

**Comment by RonnyPfannschmidt** [comment]
i recall there are some platform bugs with that one that did hit other projects as well

i dont have one availiable to me, so it might take some time to fix this one

**Comment by yoloseem** [comment]
@RonnyPfannschmidt Thanks for fast response. However, there was my misidentification. There was `-p no:tmpdir` option in my `pytest.ini`'s `addopts` and it was the actual cause.

I'll open further pull request for that in advance.

**Comment by RonnyPfannschmidt** [comment]
interesting find - a fix for tmpdir being disabled would be appreciated

**Comment by yoloseem** [comment]
oh... Pull request was my mistyped word for `issue`. -_-;;; Anyway I will investigate on that.
