### ISSUE TITLE
Cannot run with -p no:tmpdir option

### ISSUE THREAD

**Issue by yoloseem** [pytest-dev/pytest-xdist#22]
When I use xdist option with `-p no:tmpdir` also set, it causes `AttributeError: 'Config' object has no attribute '_tmpdirhandler'`:
```bash
$ py.test -n auto -p no:tmpdir test.py
================================================= test session starts ==================================================
platform darwin -- Python 2.7.9, pytest-2.8.3, py-1.4.31, pluggy-0.3.1
django settings: proj.settings.local (from environment variable)
rootdir: /Users/khj/works/projrepo/pmc3, inifile: pytest.ini
plugins: cov-2.1.0, django-2.9.1, xdist-1.13.1
gw0 C / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 IINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/_pytest/main.py", line 88, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/xdist/dsession.py", line 494, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/xdist/slavemanage.py", line 45, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/xdist/slavemanage.py", line 54, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File "/Users/khj/.pyenv/versions/proj/lib/python2.7/site-packages/xdist/slavemanage.py", line 216, in setup
INTERNALERROR>     basetemp = self.config._tmpdirhandler.getbasetemp()
INTERNALERROR> AttributeError: 'Config' object has no attribute '_tmpdirhandler'
```

System info:
```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11
BuildVersion:	15A284
$ pip freeze | grep -i pytest
pytest==2.8.3
pytest-cov==2.1.0
pytest-django==2.9.1
pytest-xdist==1.13.1
```

**Comment by nicoddemus** [comment]
Hmm this might be fixed already in the features branch, due to fixes in how configuration options are transferred to workers...

**Comment by yoloseem** [comment]
Issue reproduced with `pytest-2.9.0.dev1` (`$ pip install git+https://github.com/pytest-dev/pytest.git@features`).

@nicoddemus do you have any idea to try myself in advance?

**Comment by nicoddemus** [comment]
Sorry, now that I took a look at the code it's clear that it is a distx bug... Unfortunately there's no workaround, we'll have to work on a fix. 

Out of curiosity, why are you disabling tmpdir?

**Comment by yoloseem** [comment]
@nicoddemus In my proj, there was an implementation causing error due to conflicts with tmpdir of pytest, but I can't remember the details :-/  I've just checked without tmpdir, however suddenly the issue has gone....

**Comment by nicoddemus** [comment]
You mean re-enabling tmpdir fixed this issue?

**Comment by yoloseem** [comment]
@nicoddemus No. I mean that I don't need to use `-p no:tmpdir` for testing my project anymore. But xdist still fails with disabling tmpdir.

**Comment by hpk42** [comment]
disabling a builtin plugin is bound to give problems.  IOW, xdist relies on a builtin plugin which is kind of fine.  Maybe someone can check h ow easy it would be to allow xdist to run with no:tmpdir but otherwise i suggest to close the issue.

**Comment by nicoddemus** [comment]
> No. I mean that I don't need to use -p no:tmpdir for testing my project anymore.

That's what I meant by "re-enabling tmpdir". :grin: sorry for not being clearer. 

@hpk42 I will take a look today, should be simple and I think it's worth it, as the message received by the user is not friendly.

**Comment by yoloseem** [comment]
Awesome. Thanks!
