### ISSUE TITLE
xdist + flaky + xfail causes xdist to raise an exception

### ISSUE THREAD

**Issue by dshuga** [pytest-dev/pytest-xdist#222]
If (and only if) I'm using both xdist and flaky and a test xfails, I get this exception when the tests finish running:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/var/local/jenkins/qa/workspace/shield-itaw-parallel/venv/lib/python3.6/site-packages/_pytest/main.py", line 110, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/var/local/jenkins/qa/workspace/shield-itaw-parallel/venv/lib/python3.6/site-packages/_pytest/main.py", line 146, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/var/local/jenkins/qa/workspace/shield-itaw-parallel/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/var/local/jenkins/qa/workspace/shield-itaw-parallel/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/var/local/jenkins/qa/workspace/shield-itaw-parallel/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/var/local/jenkins/qa/workspace/shield-itaw-parallel/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/var/local/jenkins/qa/workspace/shield-itaw-parallel/venv/lib/python3.6/site-packages/xdist/dsession.py", line 114, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/var/local/jenkins/qa/workspace/shield-itaw-parallel/venv/lib/python3.6/site-packages/xdist/dsession.py", line 133, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/var/local/jenkins/qa/workspace/shield-itaw-parallel/venv/lib/python3.6/site-packages/xdist/dsession.py", line 239, in slave_testreport
INTERNALERROR>     self.sched.mark_test_complete(node, rep.item_index, rep.duration)
INTERNALERROR>   File "/var/local/jenkins/qa/workspace/shield-itaw-parallel/venv/lib/python3.6/site-packages/xdist/scheduler/load.py", line 152, in mark_test_complete
INTERNALERROR>     self.node2pending[node].remove(item_index)
INTERNALERROR> ValueError: list.remove(x): x not in list
```

I'm using pytest 3.2.1, flaky 3.4.0, and xdist 1.19.1

---
editted by @nicoddemus: formatting

**Comment by nicoddemus** [comment]
Thanks for the report. I believe this might be fixed by #218, which has not been released yet though. Could you test it by installing from the latest `master` to confirm?

```
pip install git+https://github.com/pytest-dev/pytest-xdist
```

**Comment by dshuga** [comment]
That does indeed fix the problem. Thanks for the quick response!

**Comment by nicoddemus** [comment]
Thanks for confirming!
