### ISSUE TITLE
Please help "ModuleNotFoundError: No module named 'urllib2'"

### ISSUE THREAD

**Issue by UANEMESISUA** [pytest-dev/pytest-xdist#240]
`PS C:\FULL\GNS READY SCRIPTS> pytest -n5 --driver Chrome load_for_itea.py --max-slave-restart=2 -v
============================= test session starts =============================
platform win32 -- Python 3.6.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- c:\python36\python.exe
cachedir: .cache
driver: Chrome
sensitiveurl: .*
metadata: {'Python': '3.6.3', 'Platform': 'Windows-10-10.0.15063-SP0', 'Packages': {'pytest': '3.2.3', 'py': '1.4.34', 'pluggy': '0.4.0'}, 'Plugins': {'xdist': '1.20.1', 'variables': '1.7.0', 'selenium': '1.11.1', 'metadata': '1.5.0', 'html': '1.16.0', 'forked': '0.2', 'base-url': '1.4.1'}, 'JAVA_HOME': 'C:\\Program Files\\Java\\jdk1.8.0_131\\bin', 'Base URL': '', 'Driver': 'Chrome', 'Capabilities': {}}
rootdir: C:\FULL\GNS READY SCRIPTS, inifile:
plugins: xdist-1.20.1, variables-1.7.0, selenium-1.11.1, metadata-1.5.0, html-1.16.0, forked-0.2, base-url-1.4.1
[gw0] win32 Python 3.6.3 cwd: C:\FULL\GNS READY SCRIPTS
[gw1] win32 Python 3.6.3 cwd: C:\FULL\GNS READY SCRIPTS
[gw2] win32 Python 3.6.3 cwd: C:\FULL\GNS READY SCRIPTS
[gw3] win32 Python 3.6.3 cwd: C:\FULL\GNS READY SCRIPTS
[gw4] win32 Python 3.6.3 cwd: C:\FULL\GNS READY SCRIPTS
gw0 C / gw1 C / gw2 C / gw3 C / gw4 C[gw0] node down: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\_pytest\config.py", line 443, in import_plugin
    __import__(importspec)
  File "c:\python36\lib\site-packages\_pytest\cacheprovider.py", line 10, in <module>
    import json
  File "C:\FULL\GNS READY SCRIPTS\json.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\execnet\gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 12, in <module>
  File "c:\python36\lib\site-packages\pytest.py", line 77, in <module>
    _preloadplugins()  # to populate pytest.* namespace so help(pytest) works
  File "c:\python36\lib\site-packages\_pytest\config.py", line 118, in _preloadplugins
    _preinit.append(get_config())
  File "c:\python36\lib\site-packages\_pytest\config.py", line 128, in get_config
    pluginmanager.import_plugin(spec)
  File "c:\python36\lib\site-packages\_pytest\config.py", line 450, in import_plugin
    raise new_exc
ImportError: Error importing plugin "cacheprovider": No module named 'urllib2'

Replacing crashed slave gw0
[gw5] win32 Python 3.6.3 cwd: C:\FULL\GNS READY SCRIPTS
gw5 C / gw1 C / gw2 C / gw3 C / gw4 C[gw1] node down: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\_pytest\config.py", line 443, in import_plugin
    __import__(importspec)
  File "c:\python36\lib\site-packages\_pytest\cacheprovider.py", line 10, in <module>
    import json
  File "C:\FULL\GNS READY SCRIPTS\json.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\execnet\gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 12, in <module>
  File "c:\python36\lib\site-packages\pytest.py", line 77, in <module>
    _preloadplugins()  # to populate pytest.* namespace so help(pytest) works
  File "c:\python36\lib\site-packages\_pytest\config.py", line 118, in _preloadplugins
    _preinit.append(get_config())
  File "c:\python36\lib\site-packages\_pytest\config.py", line 128, in get_config
    pluginmanager.import_plugin(spec)
  File "c:\python36\lib\site-packages\_pytest\config.py", line 450, in import_plugin
    raise new_exc
ImportError: Error importing plugin "cacheprovider": No module named 'urllib2'

Replacing crashed slave gw1
[gw6] win32 Python 3.6.3 cwd: C:\FULL\GNS READY SCRIPTS
gw5 C / gw6 C / gw2 C / gw3 C / gw4 C[gw2] node down: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\_pytest\config.py", line 443, in import_plugin
    __import__(importspec)
  File "c:\python36\lib\site-packages\_pytest\cacheprovider.py", line 10, in <module>
    import json
  File "C:\FULL\GNS READY SCRIPTS\json.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\execnet\gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 12, in <module>
  File "c:\python36\lib\site-packages\pytest.py", line 77, in <module>
    _preloadplugins()  # to populate pytest.* namespace so help(pytest) works
  File "c:\python36\lib\site-packages\_pytest\config.py", line 118, in _preloadplugins
    _preinit.append(get_config())
  File "c:\python36\lib\site-packages\_pytest\config.py", line 128, in get_config
    pluginmanager.import_plugin(spec)
  File "c:\python36\lib\site-packages\_pytest\config.py", line 450, in import_plugin
    raise new_exc
ImportError: Error importing plugin "cacheprovider": No module named 'urllib2'

Maximum crashed slaves reached: 2
[gw3] node down: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\_pytest\config.py", line 443, in import_plugin
    __import__(importspec)
  File "c:\python36\lib\site-packages\_pytest\cacheprovider.py", line 10, in <module>
    import json
  File "C:\FULL\GNS READY SCRIPTS\json.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\execnet\gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 12, in <module>
  File "c:\python36\lib\site-packages\pytest.py", line 77, in <module>
    _preloadplugins()  # to populate pytest.* namespace so help(pytest) works
  File "c:\python36\lib\site-packages\_pytest\config.py", line 118, in _preloadplugins
    _preinit.append(get_config())
  File "c:\python36\lib\site-packages\_pytest\config.py", line 128, in get_config
    pluginmanager.import_plugin(spec)
  File "c:\python36\lib\site-packages\_pytest\config.py", line 450, in import_plugin
    raise new_exc
ImportError: Error importing plugin "cacheprovider": No module named 'urllib2'

Maximum crashed slaves reached: 2
[gw4] node down: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\_pytest\config.py", line 443, in import_plugin
    __import__(importspec)
  File "c:\python36\lib\site-packages\_pytest\cacheprovider.py", line 10, in <module>
    import json
  File "C:\FULL\GNS READY SCRIPTS\json.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\execnet\gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 12, in <module>
  File "c:\python36\lib\site-packages\pytest.py", line 77, in <module>
    _preloadplugins()  # to populate pytest.* namespace so help(pytest) works
  File "c:\python36\lib\site-packages\_pytest\config.py", line 118, in _preloadplugins
    _preinit.append(get_config())
  File "c:\python36\lib\site-packages\_pytest\config.py", line 128, in get_config
    pluginmanager.import_plugin(spec)
  File "c:\python36\lib\site-packages\_pytest\config.py", line 450, in import_plugin
    raise new_exc
ImportError: Error importing plugin "cacheprovider": No module named 'urllib2'

Maximum crashed slaves reached: 2
[gw5] node down: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\_pytest\config.py", line 443, in import_plugin
    __import__(importspec)
  File "c:\python36\lib\site-packages\_pytest\cacheprovider.py", line 10, in <module>
    import json
  File "C:\FULL\GNS READY SCRIPTS\json.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\execnet\gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 12, in <module>
  File "c:\python36\lib\site-packages\pytest.py", line 77, in <module>
    _preloadplugins()  # to populate pytest.* namespace so help(pytest) works
  File "c:\python36\lib\site-packages\_pytest\config.py", line 118, in _preloadplugins
    _preinit.append(get_config())
  File "c:\python36\lib\site-packages\_pytest\config.py", line 128, in get_config
    pluginmanager.import_plugin(spec)
  File "c:\python36\lib\site-packages\_pytest\config.py", line 450, in import_plugin
    raise new_exc
ImportError: Error importing plugin "cacheprovider": No module named 'urllib2'

Maximum crashed slaves reached: 2
[gw6] node down: Traceback (most recent call last):
  File "c:\python36\lib\site-packages\_pytest\config.py", line 443, in import_plugin
    __import__(importspec)
  File "c:\python36\lib\site-packages\_pytest\cacheprovider.py", line 10, in <module>
    import json
  File "C:\FULL\GNS READY SCRIPTS\json.py", line 5, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\execnet\gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 12, in <module>
  File "c:\python36\lib\site-packages\pytest.py", line 77, in <module>
    _preloadplugins()  # to populate pytest.* namespace so help(pytest) works
  File "c:\python36\lib\site-packages\_pytest\config.py", line 118, in _preloadplugins
    _preinit.append(get_config())
  File "c:\python36\lib\site-packages\_pytest\config.py", line 128, in get_config
    pluginmanager.import_plugin(spec)
  File "c:\python36\lib\site-packages\_pytest\config.py", line 450, in import_plugin
    raise new_exc
ImportError: Error importing plugin "cacheprovider": No module named 'urllib2'

Maximum crashed slaves reached: 2`

**Comment by RonnyPfannschmidt** [comment]
as far as i can tell your local folder hide modules of the stdlib, which in turn breaks pytest

json is a stdlib one for example

**Comment by UANEMESISUA** [comment]
How can I fix this?

**Comment by nicoddemus** [comment]
The file `C:\FULL\GNS READY SCRIPTS\json.py` has the same name as the builtin module `json`. Pytest tries to import `json` (the builtin) but gets `C:\FULL\GNS READY SCRIPTS\json.py`, which in turn tries to import `urllib2` which is not available in Python 3.

We are not sure how to help further because we don't know anything about this setup. Is this your code? Is this meant to run with Python 3? etc.

**Comment by UANEMESISUA** [comment]
Thank u!
