### ISSUE TITLE
xdist plugin causes run to faildue to lack of syslog module on windows

### ISSUE THREAD

**Issue by prasanth-varikallu** [pytest-dev/pytest-xdist#245]
All I did was install pytest, pytest-xdist

start execution with pytest -n 8

The run fails with the below error:

[Step 3/3] INTERNALERROR>     import syslog
[17:43:23][Step 3/3] INTERNALERROR> ModuleNotFoundError: No module named 'syslog'

**Comment by nicoddemus** [comment]
Hi @prasanth-varikallu thanks for the report.

This has been fixed with the release of `py-1.5.2`. Please update your environment with `pytest install py -U` and it should work.

**Comment by prasanth-varikallu** [comment]
I'm using the latest version of pytest-xdist(1.20.1). I just found that the previous runs used the same version of pytest-xdist and were able to run without any issues. So I assume it appears like the issue is caused by something else. But the stacktrace shows it's from pytest-xdist. I'm confused. Does it make any sense to you?


[17:43:14][Step 1/3] Successfully installed Pillow-4.1.1 Unidecode-0.4.21 apipkg-1.4 awesome-slugify-1.6.5 certifi-2017.11.5 chardet-3.0.4 colorama-0.3.9 execnet-1.5.0 future-0.16.0 idna-2.6 ldap3-2.4 nose-1.3.7 nose-testconfig-0.10 olefile-0.44 py-1.5.1 pyasn1-0.3.7 pymongo-3.5.1 pyodbc-4.0.21 pytest-3.2.2 pytest-forked-0.2 pytest-xdist-1.20.1 
[17:43:18][Step 1/3] Collecting teamcity-messages
[17:43:19][Step 1/3] Installing collected packages: teamcity-messages
[17:43:19][Step 1/3] Successfully installed teamcity-messages-1.21
[17:43:19][Step 1/3] Process exited with code 0
[17:43:19]Step 2/3: Install teamcity-messages (Command Line) (1s)
[17:43:21]Step 3/3: Execute Tests (pytests) (Command Line) (2s)
[17:43:21][Step 3/3] Starting: E:\TeamCity\environment\scripts\pytest.exe tests --env=dev -n 8
[17:43:21][Step 3/3] in directory: E:\TeamCity
[17:43:23][Step 3/3] INTERNALERROR> Traceback (most recent call last):
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\_pytest\main.py", line 106, in wrap_session
[17:43:23][Step 3/3] INTERNALERROR>     config._do_configure()
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\_pytest\config.py", line 935, in _do_configure
[17:43:23][Step 3/3] INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 750, in call_historic
[17:43:23][Step 3/3] INTERNALERROR>     self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 339, in _hookexec
[17:43:23][Step 3/3] INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 334, in <lambda>
[17:43:23][Step 3/3] INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 614, in execute
[17:43:23][Step 3/3] INTERNALERROR>     res = hook_impl.function(*args)
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\xdist\plugin.py", line 95, in pytest_configure
[17:43:23][Step 3/3] INTERNALERROR>     from xdist.dsession import DSession
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\_pytest\assertion\rewrite.py", line 212, in load_module
[17:43:23][Step 3/3] INTERNALERROR>     py.builtin.exec_(co, mod.__dict__)
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\xdist\dsession.py", line 5, in <module>
[17:43:23][Step 3/3] INTERNALERROR>     from xdist.scheduler import (
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\xdist\scheduler\__init__.py", line 1, in <module>
[17:43:23][Step 3/3] INTERNALERROR>     from xdist.scheduler.each import EachScheduling  # noqa
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\_pytest\assertion\rewrite.py", line 212, in load_module
[17:43:23][Step 3/3] INTERNALERROR>     py.builtin.exec_(co, mod.__dict__)
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\xdist\scheduler\each.py", line 1, in <module>
[17:43:23][Step 3/3] INTERNALERROR>     from py.log import Producer
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\py\_vendored_packages\apipkg.py", line 148, in __makeattr
[17:43:23][Step 3/3] INTERNALERROR>     result = importobj(modpath, attrname)
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\py\_vendored_packages\apipkg.py", line 69, in importobj
[17:43:23][Step 3/3] INTERNALERROR>     module = __import__(modpath, None, None, ['__doc__'])
[17:43:23][Step 3/3] INTERNALERROR>   File "e:\teamcity\environment\lib\site-packages\py\_log\log.py", line 19, in <module>
[17:43:23][Step 3/3] INTERNALERROR>     import syslog
[17:43:23][Step 3/3] INTERNALERROR> ModuleNotFoundError: No module named 'syslog'
[17:43:23][Step 3/3] Process exited with code 3

**Comment by nicoddemus** [comment]
You `py` version should be `1.5.2`. What does `pip list` shows for you?

**Comment by prasanth-varikallu** [comment]
My bad!!! I didn't realize you're talking about a module called 'py'. I do now. I currently have 1.4.34. I updated it to 1.5.2 and the issue is resolved. Thank you for your help +1

**Comment by nicoddemus** [comment]
👍
