### ISSUE TITLE
Node down when number of workers are increased. 

### ISSUE THREAD

**Issue by shireenabraham** [pytest-dev/pytest-xdist#251]
When given this ini file the test suite executes correctly
[pytest]
addopts = -n 5 --dist load --boxed --timeout=90 -v --durations=32 --lf
norecursedirs = ui zetc gracefulShutdown

gw0 = dialplan conf/AgentLogin
gw1 = conf/DN 
gw2 = dm/AdvancedSearch dm/Bulk dm/CME  dm/IVR dm/Profile
gw3 = voicemail conf/AgentGroup conf/System monitoring tserv 
gw4 = conf/Person conf/Place dm/Device dm/Features dm/FirmwareUpgrade

When number of workers are increased to 9. The test suite fails

[pytest]
addopts = -n 9 --dist load --boxed --timeout=90 -v --durations=32 --lf
norecursedirs = ui zetc gracefulShutdown

gw0 = dialplan monitoring
gw1 = voicemail dm/Profile
gw2 = conf/AgentLogin dm/Device 
gw3 = conf/DN dm/Bulk
gw4 = conf/Person dm/CME
gw5 = conf/Place dm/Features    
gw6 = conf/AgentGroup dm/IVR 
gw7 = conf/System dm/FirmwareUpgrade
gw8 = dm/AdvancedSearch tserv
 
it fails with the following error

[gw8] node down: Traceback (most recent call last):
  File "/var/lib/jenkins/jobs/fs-integration-test-standalone/workspace/env27/lib/python2.7/site-packages/execnet/gateway_base.py", line 816, in _local_receive
    callback(data)   # even if channel may be already closed
  File "/var/lib/jenkins/jobs/fs-integration-test-standalone/workspace/env27/src/pytest-xdist/xdist/slavemanage.py", line 316, in process_from_remote
    self.config.pluginmanager.notify_exception(excinfo)
AttributeError: 'PytestPluginManager' object has no attribute 'notify_exception'

I have searched but couldn't find the possible reasons for the error.

**Comment by nicoddemus** [comment]
Hi @shireenabraham 

Which version are you using? Your traceback says:

```
File ".../pytest-xdist/xdist/slavemanage.py", line 316, in process_from_remote
  self.config.pluginmanager.notify_exception(excinfo)
AttributeError: 'PytestPluginManager' object has no attribute 'notify_exception'
```

But `slavemanage.py:316` currently contains this code:

https://github.com/pytest-dev/pytest-xdist/blob/5889e4c2290fdd7422f4d928f8b345080e787e5c/xdist/slavemanage.py#L316-L318

And what does this mean?

```
gw0 = dialplan monitoring
gw1 = voicemail dm/Profile
gw2 = conf/AgentLogin dm/Device
gw3 = conf/DN dm/Bulk
gw4 = conf/Person dm/CME
gw5 = conf/Place dm/Features
gw6 = conf/AgentGroup dm/IVR
gw7 = conf/System dm/FirmwareUpgrade
gw8 = dm/AdvancedSearch tserv
```

**Comment by nicoddemus** [comment]
Hmm your code seems to be using the code changed by this commit: https://github.com/pytest-dev/pytest-xdist/commit/64f8ad54693b3a0f7608ba0fb3b9f123fc06ef9e, which was included in `1.18.2`. That was a tricky one because it would actually hide the original error. I suggest to update `pytest-xdist` to see if you get a different behavior.

**Comment by shireenabraham** [comment]
gw0 = dialplan monitoring
gw1 = voicemail dm/Profile
gw2 = conf/AgentLogin dm/Device
gw3 = conf/DN dm/Bulk
gw4 = conf/Person dm/CME
gw5 = conf/Place dm/Features
gw6 = conf/AgentGroup dm/IVR
gw7 = conf/System dm/FirmwareUpgrade
gw8 = dm/AdvancedSearch tserv
The above are test cases I have distributed among the workers. I have done this to reduce the execution time. How do I check the version of pytest-xdist ?

**Comment by RonnyPfannschmidt** [comment]
pytest outputs the version at the start of a test run, and you can let pip list the versions of packages

**Comment by shireenabraham** [comment]
pytest-2.5.2 is the version used.  The pytest executes when I use 8 workers, but fails when I use 9 or more
