### ISSUE TITLE
pytest-xdist does not work, produces long stack trace

### ISSUE THREAD

**Issue by nicbou** [pytest-dev/pytest-xdist#254]
I get the following stack trace when running my tests with `-n3` or any other variation that involves tests running in parallel:

```
====================================================================================================================================== test session starts =======================================================================================================================================
platform linux -- Python 3.5.2, pytest-3.3.0, py-1.5.2, pluggy-0.6.0 -- /usr/bin/python3
cachedir: .cache
rootdir: /app, inifile: pytest.ini
plugins: xdist-1.20.1, forked-0.2
gw0 I / gw1 I / gw2 IINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/_pytest/main.py", line 101, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/xdist/dsession.py", line 80, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/xdist/slavemanage.py", line 64, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/xdist/slavemanage.py", line 69, in setup_node
INTERNALERROR>     self.config.hook.pytest_xdist_newgateway(gateway=gw)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/xdist/dsession.py", line 351, in pytest_xdist_newgateway
INTERNALERROR>     rinfo = gateway._rinfo()
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/execnet/gateway.py", line 79, in _rinfo
INTERNALERROR>     ch = self.remote_exec(rinfo_source)
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/execnet/gateway.py", line 126, in remote_exec
INTERNALERROR>     channel = self.newchannel()
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/execnet/gateway_base.py", line 1002, in newchannel
INTERNALERROR>     return self._channelfactory.new()
INTERNALERROR>   File "/usr/local/lib/python3.5/dist-packages/execnet/gateway_base.py", line 779, in new
INTERNALERROR>     raise IOError("connexion already closed: %s" % (self.gateway,))
INTERNALERROR> OSError: connexion already closed: <Gateway id='gw0' not-receiving, thread model, 0 active channels>
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/execnet/gateway_base.py", line 201, in get
    return self._result
AttributeError: 'Reply' object has no attribute '_result'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/execnet/gateway_base.py", line 213, in run
    self._result = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/execnet/multi.py", line 288, in termkill
    termreply.get(timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/execnet/gateway_base.py", line 203, in get
    reraise(*(self._excinfo[:3]))  # noqa
  File "<string>", line 2, in reraise
  File "/usr/local/lib/python3.5/dist-packages/execnet/gateway_base.py", line 213, in run
    self._result = func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/execnet/multi.py", line 200, in join_wait
    gw._io.wait()
  File "/usr/local/lib/python3.5/dist-packages/execnet/gateway_io.py", line 25, in wait
    return self.popen.wait()
  File "/usr/local/lib/python3.5/dist-packages/gevent/subprocess.py", line 1345, in wait
    return self._gevent_result_wait(timeout, _raise_exc)
  File "/usr/local/lib/python3.5/dist-packages/gevent/subprocess.py", line 731, in _gevent_result_wait
    result = self.result.wait(timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 421, in wait
    return self._wait(timeout)
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 129, in _wait
    gotit = self._wait_core(timeout)
  File "/usr/local/lib/python3.5/dist-packages/gevent/event.py", line 106, in _wait_core
    result = self.hub.switch()
  File "/usr/local/lib/python3.5/dist-packages/gevent/hub.py", line 630, in switch
    return RawGreenlet.switch(self)
greenlet.error: cannot switch to a different thread
```

Here are my installed packages. They are running on Python 3 inside a ubuntu16.04 docker container:

```
apipkg==1.4
attrs==17.3.0
boto3==1.4.7
botocore==1.7.48
docutils==0.14
execnet==1.5.0
gevent==1.2.2
greenlet==0.4.12
grequests==0.3.0
jmespath==0.9.3
pdfrw==0.3
pluggy==0.6.0
py==1.5.2
pymongo==3.4.0
pytest==3.3.0
pytest-forked==0.2
pytest-xdist==1.20.1
python-dateutil==2.6.1
requests==2.13.0
s3transfer==0.1.12
six==1.11.0
tqdm==4.14.0
```

Pytest.ini:

```
[pytest]
python_files=*_test.py *_test.regression.py
```

I wish I could provide additional information, but I don't have the faintest clue of what any of this stack trace means.

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt hmm is `execnet` compatible with `gevent`? 🤔

**Comment by nicbou** [comment]
Here's a dependency tree, if it can help:

```
boto3==1.4.7
  - botocore [required: <1.8.0,>=1.7.0, installed: 1.7.48]
    - docutils [required: >=0.10, installed: 0.14]
    - jmespath [required: <1.0.0,>=0.7.1, installed: 0.9.3]
    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.6.1]
      - six [required: >=1.5, installed: 1.11.0]
  - jmespath [required: <1.0.0,>=0.7.1, installed: 0.9.3]
  - s3transfer [required: <0.2.0,>=0.1.10, installed: 0.1.12]
    - botocore [required: >=1.3.0,<2.0.0, installed: 1.7.48]
      - docutils [required: >=0.10, installed: 0.14]
      - jmespath [required: <1.0.0,>=0.7.1, installed: 0.9.3]
      - python-dateutil [required: >=2.1,<3.0.0, installed: 2.6.1]
        - six [required: >=1.5, installed: 1.11.0]
grequests==0.3.0
  - gevent [required: Any, installed: 1.2.2]
    - greenlet [required: >=0.4.10, installed: 0.4.12]
  - requests [required: Any, installed: 2.13.0]
pdfrw==0.3
pipdeptree==0.10.1
  - pip [required: >=6.0.0, installed: 9.0.1]
pymongo==3.4.0
pytest-xdist==1.20.1
  - execnet [required: >=1.1, installed: 1.5.0]
    - apipkg [required: >=1.4, installed: 1.4]
  - pytest [required: >=3.0.0, installed: 3.3.0]
    - attrs [required: >=17.2.0, installed: 17.3.0]
    - pluggy [required: >=0.5,<0.7, installed: 0.6.0]
    - py [required: >=1.5.0, installed: 1.5.2]
    - setuptools [required: Any, installed: 38.2.4]
    - six [required: >=1.10.0, installed: 1.11.0]
  - pytest-forked [required: Any, installed: 0.2]
    - pytest [required: >=2.6.0, installed: 3.3.0]
      - attrs [required: >=17.2.0, installed: 17.3.0]
      - pluggy [required: >=0.5,<0.7, installed: 0.6.0]
      - py [required: >=1.5.0, installed: 1.5.2]
      - setuptools [required: Any, installed: 38.2.4]
      - six [required: >=1.10.0, installed: 1.11.0]
tqdm==4.14.0
wheel==0.29.0
```

**Comment by nicbou** [comment]
Update: I removed grequests entirely, and now the tests run. There are lots of failure, but it's very likely because our tests weren't meant to run in parallel.

**Comment by nicoddemus** [comment]
I just did a quick test with `pytest-xdist` and `gevent` and it breaks quite spectacularly if I monkey patch things:

```python
from gevent import monkey; monkey.patch_all()
import pytest

@pytest.mark.parametrize('i', range(10))
def test(i):
	pass
```
```
============================= test session starts =============================
platform win32 -- Python 3.5.0, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
rootdir: C:\Users\bruno, inifile:
plugins: xdist-1.20.1, forked-0.2
gw0 [10] / gw1 [10] / gw2 okINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\_pytest\main.py", line 103, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\_pytest\main.py", line 141, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\_pytest\main.py", line 103, in wrap_session
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\_pytest\main.py", line 141, in _main
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 617, in __call__
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 180, in _multicall
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
INTERNALERROR>   File "<remote exec>", line 52, in pytest_runtestloop
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 732, in receive
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
INTERNALERROR>     x = itemqueue.get(timeout=timeout)
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "W:\Miniconda\lib\queue.py", line 164, in get
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>     self.not_empty.wait()
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "W:\Miniconda\lib\threading.py", line 293, in wait
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     waiter.acquire()
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\thread.py", line 84, in acquire
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 180, in _multicall
INTERNALERROR>     return BoundedSemaphore.acquire(self, blocking, timeout)
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "src/gevent/_semaphore.py", line 198, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4541)
INTERNALERROR>   File "<remote exec>", line 52, in pytest_runtestloop
INTERNALERROR>   File "src/gevent/_semaphore.py", line 226, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4367)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 732, in receive
INTERNALERROR>   File "src/gevent/_semaphore.py", line 166, in gevent._semaphore.Semaphore._do_wait (src/gevent/gevent._semaphore.c:3562)
INTERNALERROR>     x = itemqueue.get(timeout=timeout)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\hub.py", line 630, in switch
INTERNALERROR>   File "W:\Miniconda\lib\queue.py", line 164, in get
INTERNALERROR>     return RawGreenlet.switch(self)
INTERNALERROR>     self.not_empty.wait()
INTERNALERROR> gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x1f66d019508 select default pending=0 ref=0>)
INTERNALERROR>   File "W:\Miniconda\lib\threading.py", line 293, in wait
INTERNALERROR>     waiter.acquire()
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\thread.py", line 84, in acquire
INTERNALERROR>     return BoundedSemaphore.acquire(self, blocking, timeout)
INTERNALERROR>   File "src/gevent/_semaphore.py", line 198, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4541)
Traceback (most recent call last):
INTERNALERROR>   File "src/gevent/_semaphore.py", line 226, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4367)
  File "<string>", line 1, in <module>
INTERNALERROR>   File "src/gevent/_semaphore.py", line 166, in gevent._semaphore.Semaphore._do_wait (src/gevent/gevent._semaphore.c:3562)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\hub.py", line 630, in switch
INTERNALERROR>     return RawGreenlet.switch(self)
INTERNALERROR> gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x237aef2d508 select default pending=0 ref=0>)
  File "<string>", line 8, in <module>
Traceback (most recent call last):
  File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 1534, in serve
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
    SlaveGateway(io=io, id=id, _startcount=2).serve()
  File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 1047, in serve
  File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 1534, in serve
    self._execpool.integrate_as_primary_thread()
  File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 255, in integrate_as_primary_thread
    SlaveGateway(io=io, id=id, _startcount=2).serve()
  File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 1047, in serve
    primary_thread_task_ready.wait()
  File "W:\Miniconda\lib\threading.py", line 556, in wait
    self._execpool.integrate_as_primary_thread()
  File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 255, in integrate_as_primary_thread
    signaled = self._cond.wait(timeout)
  File "W:\Miniconda\lib\threading.py", line 293, in wait
    primary_thread_task_ready.wait()
  File "W:\Miniconda\lib\threading.py", line 556, in wait
    waiter.acquire()
  File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\thread.py", line 84, in acquire
    signaled = self._cond.wait(timeout)
  File "W:\Miniconda\lib\threading.py", line 293, in wait
    return BoundedSemaphore.acquire(self, blocking, timeout)
  File "src/gevent/_semaphore.py", line 198, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4541)
    waiter.acquire()
  File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\thread.py", line 84, in acquire
gw0 [10] / gw1 [10] / gw2 [10]  File "src/gevent/_semaphore.py", line 226, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4367)

    return BoundedSemaphore.acquire(self, blocking, timeout)
scheduling tests via LoadScheduling  File "src/gevent/_semaphore.py", line 198, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4541)

  File "src/gevent/_semaphore.py", line 166, in gevent._semaphore.Semaphore._do_wait (src/gevent/gevent._semaphore.c:3562)
  File "src/gevent/_semaphore.py", line 226, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4367)
  File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\hub.py", line 630, in switch
  File "src/gevent/_semaphore.py", line 166, in gevent._semaphore.Semaphore._do_wait (src/gevent/gevent._semaphore.c:3562)
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x1f66d019508 select default pending=0 ref=0>)
  File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x237aef2d508 select default pending=0 ref=0>)
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\_pytest\main.py", line 103, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\_pytest\main.py", line 141, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 52, in pytest_runtestloop
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 732, in receive
INTERNALERROR>     x = itemqueue.get(timeout=timeout)
INTERNALERROR>   File "W:\Miniconda\lib\queue.py", line 164, in get
INTERNALERROR>     self.not_empty.wait()
INTERNALERROR>   File "W:\Miniconda\lib\threading.py", line 293, in wait
INTERNALERROR>     waiter.acquire()
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\thread.py", line 84, in acquire
INTERNALERROR>     return BoundedSemaphore.acquire(self, blocking, timeout)
INTERNALERROR>   File "src/gevent/_semaphore.py", line 198, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4541)
INTERNALERROR>   File "src/gevent/_semaphore.py", line 226, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4367)
INTERNALERROR>   File "src/gevent/_semaphore.py", line 166, in gevent._semaphore.Semaphore._do_wait (src/gevent/gevent._semaphore.c:3562)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\hub.py", line 630, in switch
INTERNALERROR>     return RawGreenlet.switch(self)
INTERNALERROR> gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x1c53b75f508 select default pending=0 ref=0>)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
  File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 1534, in serve
    SlaveGateway(io=io, id=id, _startcount=2).serve()
  File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 1047, in serve
    self._execpool.integrate_as_primary_thread()
  File "c:\users\bruno\.env36-tmp\lib\site-packages\execnet\gateway_base.py", line 255, in integrate_as_primary_thread
    primary_thread_task_ready.wait()
  File "W:\Miniconda\lib\threading.py", line 556, in wait
    signaled = self._cond.wait(timeout)
  File "W:\Miniconda\lib\threading.py", line 293, in wait
    waiter.acquire()
  File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\thread.py", line 84, in acquire
    return BoundedSemaphore.acquire(self, blocking, timeout)
  File "src/gevent/_semaphore.py", line 198, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4541)
  File "src/gevent/_semaphore.py", line 226, in gevent._semaphore.Semaphore.acquire (src/gevent/gevent._semaphore.c:4367)
  File "src/gevent/_semaphore.py", line 166, in gevent._semaphore.Semaphore._do_wait (src/gevent/gevent._semaphore.c:3562)
  File "c:\users\bruno\.env36-tmp\lib\site-packages\gevent\hub.py", line 630, in switch
    return RawGreenlet.switch(self)
gevent.hub.LoopExit: ('This operation would block forever', <Hub at 0x1c53b75f508 select default pending=0 ref=0>)
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\_pytest\main.py", line 103, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\_pytest\main.py", line 141, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\pluggy\callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\xdist\dsession.py", line 114, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\xdist\dsession.py", line 137, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "c:\users\bruno\.env36-tmp\lib\site-packages\xdist\dsession.py", line 175, in slave_slavefinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('test_xdist.py::test[0]', <SlaveController gw2>)
INTERNALERROR> assert not 'test_xdist.py::test[0]'

======================== no tests ran in 0.57 seconds =========================
```

I I don't execute `monkey.patch_all()` the test runs normally, so I would assume `gevent` monkeypatching doesn't play well with pytest-xdist/execnet.

**Comment by nicbou** [comment]
Good catch. Here's a related ticket: https://github.com/kennethreitz/grequests/issues/55

**Comment by nicoddemus** [comment]
Thanks for the reference. I believe we can close this then.

**Comment by tzickel** [comment]
The grequests link is dead, but basically you should run when monkeypatching:
```
pytest -d --tx 3*popen//execmodel=gevent
```

**Comment by karlb** [comment]
I managed to avoid this error by excluding `subprocess` and `thread` from the monkeypatching.

**Comment by juangremes** [comment]
I was working on a project that imported a third party library, which called 
```python
from gevent import monkey; monkey.patch_all()
```
on import.
I avoided the error by running patch_all at the beginning of the test session, inside a conftest.py:
```python
def pytest_sessionstart(session):
    print("Starting pytest session...") 

    from gevent import monkey
    monkey.patch_all()
```

**Comment by RonnyPfannschmidt** [comment]
execnet is not gevent safe by default
