### ISSUE TITLE
Capturing exceptions from stdout/stderr when raised from hook in child node

### ISSUE THREAD

**Issue by westhomas** [pytest-dev/pytest-xdist#360]
I've got an internal tool that orchestrates a pytest execution using `pytest.main()`. I use this instead of using `Popen` because it allows me to pass an instantiated plugin reference to the `plugins` param, which is handy.

I'm facing a problem though with capturing exceptions when they occur in a hook raised from the child node.

Here's an example of what's not working:

```python
# test_xdist_exception.py
# see full source at https://github.com/westhomas/pytest-testapp/blob/master/test_xdist_exception.py

@pytest.hookimpl(tryfirst=True, hookwrapper=True)
def pytest_runtest_makereport(item, call):
    raise Exception('this exception is hidden by xdist in parallel mode')

# Tests
def test_foo():
    assert True

def test_foo2():
    assert True


# Doesn't work
def main():

    msg = ""

    with io.StringIO() as error_buff, \
            io.StringIO() as out_buff, \
            redirect_stderr(error_buff), \
            redirect_stdout(out_buff):

        returncode = pytest.main(['test_xdist_exception.py', '--html={}'.format('testing.html'), '-d', '--tx', '{}*popen//python=python3'.format(2), ])

        if returncode > 1 and returncode != 5:
            msg = "CRITICAL FAILURE RUNNING PYTEST: return code: {}\n".format(returncode)

        error = error_buff.getvalue()
        log_standard = out_buff.getvalue()

    print("CAPTURED ERROR")
    print("===============================")
    print(error)
    print("CAPTURED LOGS")
    print("===============================")
    print(log_standard)
    print(msg)

if __name__ == '__main__':
    main()
```

What happens when running xdist is the master exception is thrown [1]  when the child crashes but the actual exception raised from `pytest_runtest_makereport` is hidden from my attempt to capture stdout and stderr. It's *there* in the terminal output, but I can't seem to capture it using the `redirect_std*` methods.  When running without xdist, the exception is captured in stdout as desired.

I need a way to capture this exception (either in stdout or stderr) so I can log it properly. Preferably without switching over to Popen for executing a pytest session.

Any ideas?

[1]
```
# xdist crash exception
$ python3 test_xdist_exception.py
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/main.py", line 181, in wrap_session
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/main.py", line 181, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/main.py", line 221, in _main
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/main.py", line 221, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 68, in pytest_runtestloop
INTERNALERROR>   File "<remote exec>", line 82, in run_one_test
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/runner.py", line 71, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/runner.py", line 80, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/runner.py", line 168, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 174, in _multicall
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     gen = hook_impl.function(*args)
INTERNALERROR>   File "/Users/wes/work/pytest-testapp/test_xdist_exception.py", line 19, in pytest_runtest_makereport
INTERNALERROR>     raise Exception('this exception is hidden by xdist in parallel mode')
INTERNALERROR> Exception: this exception is hidden by xdist in parallel mode
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 68, in pytest_runtestloop
INTERNALERROR>   File "<remote exec>", line 82, in run_one_test
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/runner.py", line 71, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/runner.py", line 80, in runtestprotocol
INTERNALERROR>     rep = call_and_report(item, "setup", log)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/runner.py", line 168, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 174, in _multicall
INTERNALERROR>     gen = hook_impl.function(*args)
INTERNALERROR>   File "/Users/wes/work/pytest-testapp/test_xdist_exception.py", line 19, in pytest_runtest_makereport
INTERNALERROR>     raise Exception('this exception is hidden by xdist in parallel mode')
INTERNALERROR> Exception: this exception is hidden by xdist in parallel mode
CAPTURED ERROR
===============================

CAPTURED LOGS
===============================
============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.6.2, pytest-3.9.1, py-1.5.3, pluggy-0.7.1
rootdir: /Users/wes/work/pytest-testapp, inifile:
plugins: xdist-1.23.2, timeout-1.3.2, rerunfailures-4.2, metadata-1.7.0, html-1.19.0, forked-0.2
gw0 I / gw1 I
gw0 [2] / gw1 [2]

scheduling tests via LoadScheduling
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/main.py", line 181, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/_pytest/main.py", line 221, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/xdist/dsession.py", line 115, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/xdist/dsession.py", line 138, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/Users/wes/.virtualenvs/decisio/lib/python3.6/site-packages/xdist/dsession.py", line 180, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('test_xdist_exception.py::test_foo', <WorkerController gw0>)
INTERNALERROR> assert not 'test_xdist_exception.py::test_foo'

========================================================================== no tests ran in 0.56 seconds ==========================================================================

CRITICAL FAILURE RUNNING PYTEST: return code: 3
```

**Comment by nicoddemus** [comment]
Hi @westhomas, 

I don't have a specific suggestion, but just would like to comment that the workers are executed in a separate process (as you seem to know already), and the exception happens here:

https://github.com/pytest-dev/pytest-xdist/blob/3f5a8eeb7f1a00f61333064d85ec55480358ad32/xdist/remote.py#L65

That exception is then propagated to the pytest "main" which is running in the worker:

https://github.com/pytest-dev/pytest-xdist/blob/3f5a8eeb7f1a00f61333064d85ec55480358ad32/xdist/remote.py#L262

From this point I assume that execnet then fails with an exception and dumps the contents to stderr, so there's no mechanism in place to capture that exception I'm afraid.

**Comment by westhomas** [comment]
Seems I have no choice but to move over to Popen. Thanks for the info.
