### ISSUE TITLE
Required options break child processes

### ISSUE THREAD

**Issue by Hawk777** [pytest-dev/pytest-xdist#383]
```
$ cat test_stuff.py
def test_stuff():
    pass

$ cat conftest.py
import pytest
@pytest.hookimpl
def pytest_addoption(parser):
    parser.addoption("--my-option", required=True)

$ py.test --my-option=abcd
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: /tmp/test, inifile:
plugins: xdist-1.24.1, forked-0.2
collected 1 item                                                               

test_stuff.py .                                                          [100%]

=========================== 1 passed in 0.01 seconds ===========================

$ py.test --my-option=abcd -n2
============================= test session starts ==============================
platform linux -- Python 3.6.5, pytest-4.0.1, py-1.7.0, pluggy-0.8.0
rootdir: /tmp/test, inifile:
plugins: xdist-1.24.1, forked-0.2
gw0 C / gw1 Cusage: -c [options] [file_or_dir] [file_or_dir] [...]
-c: error: the following arguments are required: --my-option
[gw0] node down: Traceback (most recent call last):
  File "/tmp/venv/lib64/python3.6/site-packages/execnet/gateway_base.py", line 1072, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 263, in <module>
  File "<remote exec>", line 239, in remote_initconfig
  File "/tmp/venv/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 704, in fromdictargs
    config.parse(args, addopts=False)
  File "/tmp/venv/lib64/python3.6/site-packages/_pytest/config/__init__.py", line 851, in parse
    args, self.option, namespace=self.option
  File "/tmp/venv/lib64/python3.6/site-packages/_pytest/config/argparsing.py", line 100, in parse_setoption
    parsedoption = self.parse(args, namespace=namespace)
  File "/tmp/venv/lib64/python3.6/site-packages/_pytest/config/argparsing.py", line 80, in parse
    return self.optparser.parse_args(args, namespace=namespace)
  File "/tmp/venv/lib64/python3.6/site-packages/_pytest/config/argparsing.py", line 348, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1762, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1997, in _parse_known_args
    ', '.join(required_actions))
  File "/tmp/venv/lib64/python3.6/site-packages/_pytest/config/argparsing.py", line 344, in error
    self.exit(EXIT_USAGEERROR, _("%(prog)s: error: %(message)s\n") % args)
  File "/usr/lib64/python3.6/argparse.py", line 2376, in exit
    _sys.exit(status)
SystemExit: 4

Replacing crashed worker gw0
```

The crash and replacement of worker repeats ad infinitum until the process is killed with Ctrl+C.

**Comment by nicoddemus** [comment]
Unfortunately it is, and you are right that we don't document it properly. This is a limitation on how pytest's config is handled in the worker process, and there's been work towards refactoring this so this limitation is lifted (@RonnyPfannschmidt please correct me if I'm wrong). AFAIK this happens for options in `conftest.py` files, but works for third part plugins.

Would you like to contribute to the "FAQ" section of the docs?

**Comment by Hawk777** [comment]
If this is being worked on, perhaps it would be better to just consider it a bug like any other, and this ticket is sufficient documentation until it’s fixed? Seems to me that adding it to documentation just encourages forgetting to remove it later once the refactoring you mentioned is complete.

**Comment by nicoddemus** [comment]
Makes sense, thanks for the comment. Let's leave this open then. 👍

**Comment by RonnyPfannschmidt** [comment]
@Hawk777 it mostly works by half-accident - pytests and its integration tooling is unaware of it and cant support it at all - so it can basically only work in the most basic setups and invocation situations

**Comment by Hawk777** [comment]
OK, I didn’t realize that. The documentation for `Parser.addoption` just says “same attributes which the add_option() function of the argparse library accepts.” Does that need enhancing to explain which features you’re actually allowed to use in Pytest? Should I create a ticket accordingly on the Pytest repo itself and close this one?

**Comment by nicoddemus** [comment]
@RonnyPfannschmidt is this related to the config refactoring you are working on? (just so I know if they are related)

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus its only marginally related - the argparse config parsing details are not something i'll directly touch

**Comment by RonnyPfannschmidt** [comment]
@nicoddemus the basic gist is that the switch from optparse to argparse as done in a "pass the tests fashion" which is structurally incomplete

the "pytest" way to handle required arguments currently is to trip up on pytest-configure
