### ISSUE TITLE
DumpError during nodemanager.setup_nodes()

### ISSUE THREAD

**Issue by mitzkia** [pytest-dev/pytest-xdist#412]
While I am staring pytest with remote run (--tx) I have got the following trace:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/execnet/gateway_base.py", line 1383, in _save
INTERNALERROR>     dispatch = self._dispatch[tp]
INTERNALERROR> KeyError: <class 'pathlib2.PosixPath'>
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 201, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 258, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 67, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 61, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/xdist/dsession.py", line 81, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/xdist/workermanage.py", line 68, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/xdist/workermanage.py", line 77, in setup_node
INTERNALERROR>     node.setup()
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/xdist/workermanage.py", line 250, in setup
INTERNALERROR>     self.channel.send((self.workerinput, args, option_dict, change_sys_path))
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/execnet/gateway_base.py", line 717, in send
INTERNALERROR>     self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/execnet/gateway_base.py", line 1354, in dumps_internal
INTERNALERROR>     return _Serializer().save(obj)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/execnet/gateway_base.py", line 1372, in save
INTERNALERROR>     self._save(obj)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/execnet/gateway_base.py", line 1390, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/execnet/gateway_base.py", line 1475, in save_tuple
INTERNALERROR>     self._save(item)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/execnet/gateway_base.py", line 1390, in _save
INTERNALERROR>     dispatch(self, obj)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/execnet/gateway_base.py", line 1471, in save_dict
INTERNALERROR>     self._write_setitem(key, value)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/execnet/gateway_base.py", line 1465, in _write_setitem
INTERNALERROR>     self._save(value)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/execnet/gateway_base.py", line 1388, in _save
INTERNALERROR>     raise DumpError("can't serialize %s" % (tp,))
INTERNALERROR> execnet.gateway_base.DumpError: can't serialize <class 'pathlib2.PosixPath'>
```

It happens because one of my fixtures returns with a pathlib2.PosixPath object in my conftest.py.
I can workaround it if I cast my object to string. 
My question: could xdist handle this case?

Thanks

**Comment by RonnyPfannschmidt** [comment]
there is something  else going on, there must be a pathlib.path being passed into worker setup, that part is wrong, and a fixture cannot do it

please provide more context

**Comment by mitzkia** [comment]
@RonnyPfannschmidt Thanks for your answer.

Sorry about that, here is a minimal reproduction env.

1, pytest.ini
```
[pytest]
addopts =
            --tx id=debian-latest-192.168.9.111//ssh="-i docker/ssh-config/id_rsa 192.168.9.111 -l root//python=python3"
rsyncdirs = .
```
2, conftest.py
```
#!/usr/bin/env python

import pytest
from pathlib2 import Path


def pytest_addoption(parser):
    parser.addoption(
        "--reports",
        action="store",
        default=get_relative_report_dir(),
        help="Path for report files folder. Default form: 'reports/<current_date>'",
    )



def get_relative_report_dir():
    return Path("reports/", "subdir")
```
3, testcase
```
def test_example():
    assert True
```
4, pytest execution:
```
python3 -m pytest --dist=each test_example.py
```

**Comment by RonnyPfannschmidt** [comment]
@mitzkia thats a limitation in pytest-xdist thats not soundly fixable atm, you must use basic/simple types for options atm, a path cant be serialized (execnet related)

**Comment by nicoddemus** [comment]
Changing `default=get_relative_report_dir()` to `default=str(get_relative_report_dir())` should fix that for you.

Should we close this? I don't think we plan to add support for serialization of arbitrary objects anyway.

**Comment by mitzkia** [comment]
@RonnyPfannschmidt , @nicoddemus  Thanks for your answers.

As I said in my first comment I know that casting Path() to str will fix my problem, but it seems only a workaround (I may need it later as a Path object). This works fine until I run tests locally, but when I started to run same code remotely I will need this cast.

As this issue execnet releated maybe I will add this issue there.
