### ISSUE TITLE
--looponfail doesn't work with many processes

### ISSUE THREAD

**Issue by thedrow** [pytest-dev/pytest-xdist#42]
When I invoke py.test like this: ```py.test -n 2 --looponfail``` I get the following error:
```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/omer.katz/.virtualenvs/drifter-api/site-packages/_pytest/main.py", line 88, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/Users/omer.katz/.virtualenvs/drifter-api/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/omer.katz/.virtualenvs/drifter-api/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec

INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/omer.katz/.virtualenvs/drifter-api/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/omer.katz/.virtualenvs/drifter-api/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/omer.katz/.virtualenvs/drifter-api/site-packages/xdist/dsession.py", line 494, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/Users/omer.katz/.virtualenvs/drifter-api/site-packages/xdist/slavemanage.py", line 41, in setup_nodes
INTERNALERROR>     specs=self.specs)
INTERNALERROR>   File "/Users/omer.katz/.virtualenvs/drifter-api/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/omer.katz/.virtualenvs/drifter-api/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/omer.katz/.virtualenvs/drifter-api/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR> AttributeError: '_HookCaller' object has no attribute 'spec_opts'
```
It does trigger the error again when a file changes.

**Comment by RonnyPfannschmidt** [comment]
looponfail will be dropped from xdist,

looponfail based on the just merged cache plugin will e added to core later
it will work on xdist -n propperly

**Comment by thedrow** [comment]
:+1:
