### ISSUE TITLE
execnet==1.7.0 breaks with traceback under Windows

### ISSUE THREAD

**Issue by webknjaz** [pytest-dev/pytest-xdist#461]
ref: https://ci.appveyor.com/project/CherryPy/cheroot/builds/26599305/job/od41wbglrprs4a9n#L419
```python-traceback
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1379, in _save
    dispatch = self._dispatch[tp]
KeyError: <enum 'ExitCode'>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1068, in executetask
    do_exec(co, loc)  # noqa
  File "c:\projects\cheroot\.tox\python\lib\site-packages\xdist\remote.py", line 249, in <module>
    config.hook.pytest_cmdline_main(config=config)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\projects\cheroot\.tox\python\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "c:\projects\cheroot\.tox\python\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\projects\cheroot\.tox\python\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\_pytest\main.py", line 250, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\_pytest\main.py", line 243, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "c:\projects\cheroot\.tox\python\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "c:\projects\cheroot\.tox\python\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\xdist\remote.py", line 46, in pytest_sessionfinish
    self.sendevent("workerfinished", workeroutput=self.config.workeroutput)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\xdist\remote.py", line 31, in sendevent
    self.channel.send((name, kwargs))
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 710, in send
    self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1350, in dumps_internal
    return _Serializer().save(obj)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1368, in save
    self._save(obj)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1386, in _save
    dispatch(self, obj)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1471, in save_tuple
    self._save(item)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1386, in _save
    dispatch(self, obj)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1467, in save_dict
    self._write_setitem(key, value)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1461, in _write_setitem
    self._save(value)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1386, in _save
    dispatch(self, obj)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1467, in save_dict
    self._write_setitem(key, value)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1461, in _write_setitem
    self._save(value)
  File "c:\projects\cheroot\.tox\python\lib\site-packages\execnet\gateway_base.py", line 1384, in _save
    raise DumpError("can't serialize {}".format(tp))
execnet.gateway_base.DumpError: can't serialize <enum 'ExitCode'>
```

**Comment by RonnyPfannschmidt** [comment]
that looks like pytest updated, but xdist not

https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/remote.py#L46

part of v1.29.0

your testrun has: `plugins: cov-2.7.1, forked-1.0.2, mock-1.10.4, sugar-0.9.2, testmon-0.9.18, xdist-1.28.0`

**Comment by webknjaz** [comment]
Yeah, you're right. Thank you, Ronny!
