### ISSUE TITLE
xdist can break whe using `usercustomize`

### ISSUE THREAD

**Issue by prusse-martin** [pytest-dev/pytest-xdist#481]
When using a `usercustomize` as described in [Site-specific configuration hook¶](https://docs.python.org/3/library/site.html) I left a leftover print in the file and when running the tests with pytest and xdist I got the error:

```
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\execnet\gateway_bootstrap.py", line 32, in bootstrap_import
INTERNALERROR>     assert s == "1".encode('ascii'), repr(s)
INTERNALERROR> AssertionError: b'u'
```

The setup:
```
(_alfasim_gui-win64-py36) W:\alfasim\Projects\alfasim>cat test_a.py
def test_b():
    assert True

(_alfasim_gui-win64-py36) W:\alfasim\Projects\alfasim>cat usercustomize.py
print('usercustomize.py')

(_alfasim_gui-win64-py36) W:\alfasim\Projects\alfasim>set PYTHONPATH=.
```

Fail with xdist due to print in `usercustomize.py`:
```
(_alfasim_gui-win64-py36) W:\alfasim\Projects\alfasim>py.test -n 1 test_a.py
u
================================================= test session starts =================================================
platform win32 -- Python 3.6.7, pytest-4.5.0, py-1.7.0, pluggy-0.11.0
driver: PhantomJS
sensitiveurl: .*
PyQt5 5.6 -- Qt runtime 5.6.2 -- Qt compiled 5.6.2
rootdir: W:\alfasim\Projects\alfasim
plugins: xdist-1.29.0, variables-1.7.1, timeout-1.3.3, selenium-1.17.0, replay-0.2.2, regressions-1.0.5, qt-3.2.2, mock-1.10.0, metadata-1.8.0, localserver-0.5.0, lazy-fixture-0.5.1, html-1.22.0, forked-1.0.2, datadir-1.3.0, cpp-1.1.0, cov-2.6.1, base-url-1.4.1, hypothesis-3.57.0
gw0 IINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\_pytest\main.py", line 203, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\pluggy\manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\pluggy\manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\pluggy\callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\xdist\dsession.py", line 81, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\xdist\workermanage.py", line 64, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\xdist\workermanage.py", line 68, in setup_node
INTERNALERROR>     gw = self.group.makegateway(spec)
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\execnet\multi.py", line 128, in makegateway
INTERNALERROR>     gw = gateway_bootstrap.bootstrap(io, spec)
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\execnet\gateway_bootstrap.py", line 96, in bootstrap
INTERNALERROR>     bootstrap_import(io, spec)
INTERNALERROR>   File "W:\alfasim\envs\_alfasim_gui-win64-py36\lib\site-packages\execnet\gateway_bootstrap.py", line 32, in bootstrap_import
INTERNALERROR>     assert s == "1".encode('ascii'), repr(s)
INTERNALERROR> AssertionError: b'u'
```

No failure due to print in `usercustomize.py` (no xdist):
```
(_alfasim_gui-win64-py36) W:\alfasim\Projects\alfasim>py.test test_a.py
usercustomize.py
================================================= test session starts =================================================
platform win32 -- Python 3.6.7, pytest-4.5.0, py-1.7.0, pluggy-0.11.0
driver: PhantomJS
sensitiveurl: .*
PyQt5 5.6 -- Qt runtime 5.6.2 -- Qt compiled 5.6.2
rootdir: W:\alfasim\Projects\alfasim
plugins: xdist-1.29.0, variables-1.7.1, timeout-1.3.3, selenium-1.17.0, replay-0.2.2, regressions-1.0.5, qt-3.2.2, mock-1.10.0, metadata-1.8.0, localserver-0.5.0, lazy-fixture-0.5.1, html-1.22.0, forked-1.0.2, datadir-1.3.0, cpp-1.1.0, cov-2.6.1, base-url-1.4.1, hypothesis-3.57.0
collected 1 item

test_a.py .                                                                                                      [100%]

============================================== 1 passed in 0.01 seconds ===============================================
```

Removing `usercustomize.py` there is no failure with xdist:
```
(_alfasim_gui-win64-py36) W:\alfasim\Projects\alfasim>mv usercustomize.py usercustomize.py_

(_alfasim_gui-win64-py36) W:\alfasim\Projects\alfasim>py.test -n 1 test_a.py
================================================= test session starts =================================================
platform win32 -- Python 3.6.7, pytest-4.5.0, py-1.7.0, pluggy-0.11.0
driver: PhantomJS
sensitiveurl: .*
PyQt5 5.6 -- Qt runtime 5.6.2 -- Qt compiled 5.6.2
rootdir: W:\alfasim\Projects\alfasim
plugins: xdist-1.29.0, variables-1.7.1, timeout-1.3.3, selenium-1.17.0, replay-0.2.2, regressions-1.0.5, qt-3.2.2, mock-1.10.0, metadata-1.8.0, localserver-0.5.0, lazy-fixture-0.5.1, html-1.22.0, forked-1.0.2, datadir-1.3.0, cpp-1.1.0, cov-2.6.1, base-url-1.4.1, hypothesis-3.57.0
gw0 [1]
.                                                                                                                [100%]
============================================== 1 passed in 1.30 seconds ===============================================
```

**Comment by RonnyPfannschmidt** [comment]
this is a expected detail with execnet, it uses stdio for certain details,
the code you posted breaks the process startup prococol

**Comment by prusse-martin** [comment]
Thank you.
