### ISSUE TITLE
I want to send different testcases to the opposite machine to execute the task and report the following error

### ISSUE THREAD

**Issue by meilisong1** [pytest-dev/pytest-xdist#482]
λ python socketserver.py
socket_readline_exec_server-1.2 Entering Accept loop ('0.0.0.0', 8888)
socket_readline_exec_server-1.2 got new connection from 10.13.129.227 62499
reading line
socket_readline_exec_server-1.2 compiled source, executing
socket_readline_exec_server-1.2 finished executing code
leaving socketserver execloop
Traceback (most recent call last):
  File "socketserver.py", line 99, in <module>
    startserver(serversock, loop=False)
  File "socketserver.py", line 90, in startserver
    serversock.shutdown(2)
OSError: [WinError 10057] 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地
址，发送或接收数据的请求没有被接受。

D:\workspace\seleniumbasedemo\testcase\baidu>py.test -d --tx socket=10.13.129.53:8888 --rsyncdir  test_remote.py

**Comment by zhu-xiangtao** [comment]
@meilisong1 Hi, 
1、In my case, generated success in local site(client)
![image](https://user-images.githubusercontent.com/30288032/86205809-6d865080-bb9d-11ea-8616-9519a06ab72e.png)
2、Why occur OSError in server site, this OSError exception seems to occur in window, in centos code work fine，In socketserver.py use a fcntl module, this module belong to linux,may be related to fcntl module
