### ISSUE TITLE
xdist cause the INTERNAL errors

### ISSUE THREAD

**Issue by aaronxiang0926** [pytest-dev/pytest-xdist#493]
plugins:
forked-1.1.3,
xdist-1.30.0,
parallel-0.0.9, 
rerunfailures-7.0, 
cov-2.8.1, logger-0.5.1,
 metadata-1.8.0, html-2.0.1, 
timeout-1.3.3, repeat-0.8.0, 
instafail-0.4.1

~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-4 (140296258430720) ~~~~~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/builds/admin-ftw15/admin/sct/src/testcases/common/memory_checker.py", line 43, in run
    self._stop_event.wait(self._sleep_period)
  File "/usr/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)

~~~~~~~~~~~~~~~~~~~~~ Stack of Thread-3 (140296266823424) ~~~~~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.6/threading.py", line 884, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/viper/transports/admin_websocket/websocket_server_transport.py", line 78, in run
    srv._server = srv._event_loop.run_forever()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 422, in run_forever
    self._run_once()
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1398, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)

~~~~~~~~~~~~~~~~~~~~~ Stack of <unknown> (140296440977152) ~~~~~~~~~~~~~~~~~~~~~
  File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/execnet/gateway_base.py", line 285, in _perform_spawn
    reply.run()
  File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/execnet/gateway_base.py", line 220, in run
    self._result = func(*args, **kwargs)
  File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/execnet/gateway_base.py", line 967, in _thread_receiver
    msg = Message.from_io(io)
  File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/execnet/gateway_base.py", line 432, in from_io
    header = io.read(9)  # type 1, channel 4, payload 4
  File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/execnet/gateway_base.py", line 400, in read
    data = self._read(numbytes - len(buf))

+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/_pytest/main.py", line 213, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/_pytest/main.py", line 257, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/xdist/remote.py", line 70, in pytest_runtestloop
INTERNALERROR>     self.run_one_test(torun)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/xdist/remote.py", line 87, in run_one_test
INTERNALERROR>     self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pytest_rerunfailures.py", line 176, in pytest_runtest_protocol
INTERNALERROR>     reports = runtestprotocol(item, nextitem=nextitem, log=False)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/_pytest/runner.py", line 87, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/_pytest/runner.py", line 169, in call_and_report
INTERNALERROR>     report = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/src/testcases/conftest.py", line 169, in pytest_runtest_makereport
INTERNALERROR>     browser().save_screenshot(destination_file)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 1055, in save_screenshot
INTERNALERROR>     return self.get_screenshot_as_file(filename)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 1032, in get_screenshot_as_file
INTERNALERROR>     png = self.get_screenshot_as_png()
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 1064, in get_screenshot_as_png
INTERNALERROR>     return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 1074, in get_screenshot_as_base64
INTERNALERROR>     return self.execute(Command.SCREENSHOT)['value']
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 319, in execute
INTERNALERROR>     response = self.command_executor.execute(driver_command, params)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 374, in execute
INTERNALERROR>     return self._request(command_info[0], url, body=data)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/selenium/webdriver/remote/remote_connection.py", line 397, in _request
INTERNALERROR>     resp = self._conn.request(method, url, body=body, headers=headers)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/urllib3/request.py", line 76, in request
INTERNALERROR>     method, url, fields=fields, headers=headers, **urlopen_kw
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/urllib3/request.py", line 97, in request_encode_url
INTERNALERROR>     return self.urlopen(method, url, **extra_kw)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/urllib3/poolmanager.py", line 330, in urlopen
INTERNALERROR>     response = conn.urlopen(method, u.request_uri, **kw)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/urllib3/connectionpool.py", line 672, in urlopen
INTERNALERROR>     chunked=chunked,
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/urllib3/connectionpool.py", line 421, in _make_request
INTERNALERROR>     six.raise_from(e, None)
INTERNALERROR>   File "<string>", line 3, in raise_from
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/urllib3/connectionpool.py", line 416, in _make_request
INTERNALERROR>     httplib_response = conn.getresponse()
INTERNALERROR>   File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
INTERNALERROR>     response.begin()
INTERNALERROR>   File "/usr/lib/python3.6/http/client.py", line 297, in begin
INTERNALERROR>     version, status, reason = self._read_status()
INTERNALERROR>   File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
INTERNALERROR>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
INTERNALERROR>   File "/usr/lib/python3.6/socket.py", line 586, in readinto
INTERNALERROR>     return self._sock.recv_into(b)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pytest_timeout.py", line 140, in handler
INTERNALERROR>     timeout_sigalrm(item, params.timeout)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pytest_timeout.py", line 313, in timeout_sigalrm
INTERNALERROR>     pytest.fail('Timeout >%ss' % timeout)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/_pytest/outcomes.py", line 111, in fail
INTERNALERROR>     raise Failed(msg=msg, pytrace=pytrace)
INTERNALERROR> Failed: Timeout >90.0s
R [ 20%]
                                                                         [ 20%]
src/testcases/tests_gui/configuration/commissioning_wizard/site/legacy_coverage/test_pnp_radios.py R [ 20%]

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/_pytest/main.py", line 213, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/_pytest/main.py", line 257, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/xdist/dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/builds/admin-ftw15/admin/sct/.tox/test/lib/python3.6/site-packages/xdist/dsession.py", line 177, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('src/testcases/tests_gui/configuration/commissioning_wizard/site/lte4500_AirScale_Indoor_SFN/test_lte_opr_ac_8483_site.py::test_lte_opr_ac_8483_site', <WorkerController gw3>)
INTERNALERROR> assert not 'src/testcases/tests_gui/configuration/commissioning_wizard/site/lte4500_AirScale_Indoor_SFN/test_lte_opr_ac_8483_site.py::test_lte_opr_ac_8483_site

**Comment by nicoddemus** [comment]
Hi,

It seems your test is timing out (with `pytest-timeout`), so it is not a problem in xdist.
