### ISSUE TITLE
pytest -n 5 throw exception

### ISSUE THREAD

**Issue by 358235737** [pytest-dev/pytest-xdist#497]
while I run pytest -n 5 ,throw exception as below:
python3 -m pytest -s -v -q -n 5 TestCase --alluredir allure-results

platform linux -- Python 3.7.5, pytest-5.1.0, py-1.8.0, pluggy-0.12.0
rootdir: /app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest
plugins: allure-pytest-2.6.3, forked-1.0.2, rerunfailures-7.0, xdist-1.28.0
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I
gw0 [13] / gw1 [13] / gw2 [13] / gw3 [13] / gw4 [13]
...................
F[gw4] node down: Traceback (most recent call last):
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1374, in _save
    dispatch = self._dispatch[tp]
KeyError: <enum 'ExitCode'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1063, in executetask
    do_exec(co, loc)  # noqa
  File "<string>", line 1, in do_exec
  File "<remote exec>", line 249, in <module>
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/_pytest/main.py", line 228, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/_pytest/main.py", line 221, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "<remote exec>", line 46, in pytest_sessionfinish
  File "<remote exec>", line 31, in sendevent
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 708, in send
    self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1345, in dumps_internal
    return _Serializer().save(obj)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1363, in save
    self._save(obj)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1381, in _save
    dispatch(self, obj)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1466, in save_tuple
    self._save(item)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1381, in _save
    dispatch(self, obj)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1462, in save_dict
    self._write_setitem(key, value)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1456, in _write_setitem
    self._save(value)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1381, in _save
    dispatch(self, obj)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1462, in save_dict
    self._write_setitem(key, value)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1456, in _write_setitem
    self._save(value)
  File "/app/workspace/O2O-DDS_ISSZNFJ/o2o-dds-iss-autotest/my_virtualenvs/lib/python3.7/site-packages/execnet/gateway_base.py", line 1379, in _save
    raise DumpError("can't serialize {}".format(tp))
execnet.gateway_base.DumpError: can't serialize <enum 'ExitCode'>

Replacing crashed worker gw4

**Comment by 358235737** [comment]
duplicate with #487
resolve:
cmarqu commented Jan 8, 2020
I had this problem with pytest-xdist 1.26.1 and can confirm that it is fixed with 1.31.0.
