### ISSUE TITLE
Internal Error while trying to run tests parallel 

### ISSUE THREAD

**Issue by pythondev786** [pytest-dev/pytest-xdist#523]
**Sample Test File**
```
import pytest

def test_01():
    assert True

def test_02():
    assert False

def test_03():
    assert True

def test_04():
    assert False

def test_05():
    assert True

def test_06():
    assert False
```
**Run the test with rerun failure option. Internal error will be seen**

```
[root@arvpn ipsecanap]# python3.6 -m pytest -n 2 test_issue.py --capture no --reruns=3
=============================================================== test session starts ===============================================================
platform linux -- Python 3.6.3, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /root/regression/ipsecanap, inifile: pytest.ini
plugins: forked-0.2, env-0.6.2, metadata-1.7.0, rerunfailures-4.2, parallel-0.0.9, concurrent-0.2.2, repeat-0.8.0, html-1.19.0, xdist-1.31.0
gw0 [6] / gw1 [6]
...RINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/xdist/dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/xdist/dsession.py", line 177, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('test_issue.py::test_02', <WorkerController gw1>)
INTERNALERROR> assert not 'test_issue.py::test_02'

```
**Run the test without rerun failure option. It works fine.**

```
[root@arvpn ipsecanap]# python3.6 -m pytest -n 2 test_issue.py --capture no
=============================================================== test session starts ===============================================================
platform linux -- Python 3.6.3, pytest-5.4.1, py-1.8.1, pluggy-0.13.1
rootdir: /root/regression/ipsecanap, inifile: pytest.ini
plugins: forked-0.2, env-0.6.2, metadata-1.7.0, rerunfailures-4.2, parallel-0.0.9, concurrent-0.2.2, repeat-0.8.0, html-1.19.0, xdist-1.31.0
gw0 [6] / gw1 [6]
...FFF
==================================================================== FAILURES =====================================================================
_____________________________________________________________________ test_02 _____________________________________________________________________
[gw1] linux -- Python 3.6.3 /usr/local/bin/python3.6

    def test_02():
>       assert False
E    assert False

test_issue.py:7: AssertionError
_____________________________________________________________________ test_06 _____________________________________________________________________
[gw0] linux -- Python 3.6.3 /usr/local/bin/python3.6

    def test_06():
>       assert False
E    assert False

test_issue.py:19: AssertionError
_____________________________________________________________________ test_04 _____________________________________________________________________
[gw1] linux -- Python 3.6.3 /usr/local/bin/python3.6

    def test_04():
>       assert False
E    assert False

test_issue.py:13: AssertionError
============================================================= short test summary info =============================================================
FAILED test_issue.py::test_02 - assert False
FAILED test_issue.py::test_06 - assert False
FAILED test_issue.py::test_04 - assert False
=========================================================== 3 failed, 3 passed in 1.08s ===========================================================
[root@arvpn ipsecanap]#
```

**Environment:**

```
[root@arvpn ipsecanap]# pip3.6 list | grep 'pytest'
pytest               5.4.1
pytest-concurrent    0.2.2
pytest-env           0.6.2
pytest-forked        1.1.3
pytest-html          1.19.0
pytest-metadata      1.7.0
pytest-parallel      0.0.9
pytest-repeat        0.8.0
pytest-rerunfailures 4.2
pytest-xdist         1.31.0

```

**Comment by roksys** [comment]
I'm facing the same issue. @pythondev786 did you manage to solve it?

**Comment by pythondev786** [comment]
> I'm facing the same issue. @pythondev786 did you manage to solve it?

@roksys I think I upgraded pytest and pytest-xdist to solve this issue. Here is my current environment 

`pytest                6.0.2
pytest-forked         1.0.2
pytest-ordering       0.6
pytest-repeat         0.8.0
pytest-rerunfailures  9.0
pytest-xdist          2.1.0
`

**Comment by nicoddemus** [comment]
Closing this for now, others should always try to upgrade pytest-xdist and pytest to latest version when facing this problem. If that still doesn't solve the problem, then please post an issue!
