### ISSUE TITLE
How do I specify a port for SSH

### ISSUE THREAD

**Issue by hroncok** [pytest-dev/pytest-xdist#53]
How do I specify a port for SSH? I cannot find any information about that. Thanks

**Comment by spinus** [comment]
Not sure if it's the case, but you could try to setting up and alias in ~/.ssh/config (and configure hostname,port, user there) and use that alias in xdist

**Comment by RonnyPfannschmidt** [comment]
`ssh=-p 5000 myhost` is an example straight out of http://codespeak.net/execnet/basics.html#examples-for-valid-gateway-specifications

i'd appreciate suggestions for getting that across better

**Comment by hroncok** [comment]
```
$ py.test-3 -d --tx ssh=-p 2222 127.0.0.1 --rsyncdir license license
======================================================================================================= test session starts =======================================================================================================
platform linux -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.3
rootdir: .../license, inifile: 
plugins: testmon, xdist, xdist, xdist
gw0 IBad port 'python -c "import sys;exec(eval(sys.stdin.readline()))"'
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/churchyard/.local/lib/python3.4/site-packages/execnet/gateway_bootstrap.py", line 41, in bootstrap_exec
INTERNALERROR>     s = io.read(1)
INTERNALERROR>   File "/home/churchyard/.local/lib/python3.4/site-packages/execnet/gateway_base.py", line 389, in read
INTERNALERROR>     "expected %d bytes, got %d" % (numbytes, len(buf)))
INTERNALERROR> EOFError: expected 1 bytes, got 0
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python3.4/site-packages/_pytest/main.py", line 82, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/lib/python3.4/site-packages/_pytest/core.py", line 521, in __call__
INTERNALERROR>     return self._docall(self.methods, kwargs)
INTERNALERROR>   File "/usr/lib/python3.4/site-packages/_pytest/core.py", line 528, in _docall
INTERNALERROR>     firstresult=self.firstresult).execute()
INTERNALERROR>   File "/usr/lib/python3.4/site-packages/_pytest/core.py", line 394, in execute
INTERNALERROR>     res = method(*args)
INTERNALERROR>   File "/home/churchyard/.local/lib/python3.4/site-packages/xdist/dsession.py", line 509, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "/home/churchyard/.local/lib/python3.4/site-packages/xdist/slavemanage.py", line 48, in setup_nodes
INTERNALERROR>     nodes.append(self.setup_node(spec, putevent))
INTERNALERROR>   File "/home/churchyard/.local/lib/python3.4/site-packages/xdist/slavemanage.py", line 52, in setup_node
INTERNALERROR>     gw = self.group.makegateway(spec)
INTERNALERROR>   File "/home/churchyard/.local/lib/python3.4/site-packages/execnet/multi.py", line 128, in makegateway
INTERNALERROR>     gw = gateway_bootstrap.bootstrap(io, spec)
INTERNALERROR>   File "/home/churchyard/.local/lib/python3.4/site-packages/execnet/gateway_bootstrap.py", line 94, in bootstrap
INTERNALERROR>     bootstrap_exec(io, spec)
INTERNALERROR>   File "/home/churchyard/.local/lib/python3.4/site-packages/execnet/gateway_bootstrap.py", line 46, in bootstrap_exec
INTERNALERROR>     raise HostNotFound(io.remoteaddress)
INTERNALERROR> execnet.gateway_bootstrap.HostNotFound: -p
```

When I tried first, I've tryed adding port after `:`, the same way as with socket.

**Comment by hroncok** [comment]
```
$ py.test-3 -d --tx ssh="-p 2222 127.0.0.1" --rsyncdir . license
======================================================================================================= test session starts =======================================================================================================
platform linux -- Python 3.4.3 -- py-1.4.30 -- pytest-2.7.3
rootdir: .../license, inifile: 
plugins: testmon, xdist, xdist, xdist
gw0 C
```

And it hangs. Don't know if that's relevant with the port.

**Comment by hroncok** [comment]
The problem is not related to the port thing.

Both solutions (alias, or the thing @RonnyPfannschmidt mentioned) work for specifying the port.

**Comment by hroncok** [comment]
If anyone gets the same problem, it was caused by wrogn version of python picked up form the remote environment and it was fixed by this:

    py.test-3 -d --tx 'ssh=mac//python=/usr/local/bin/python3' --rsyncdir license license --rsyncdir test test
