### ISSUE TITLE
Bad `-k` selection causes internal error on worker nodes

### ISSUE THREAD

**Issue by Zac-HD** [pytest-dev/pytest-xdist#539]
```bash
$ echo 'def test_foo(): pass' > t.py
$ pytest t.py -k 'no bar'
platform win32 -- Python 3.7.2, pytest-5.4.3, py-1.8.0, pluggy-0.12.0
...
collected 1 item
============================ no tests ran in 0.02s ============================
ERROR: Wrong expression passed to '-k': no bar
```

Obviously this should be `-k 'not bar'`, but running under xdist I get an internal error instead of the helpful message here:

```
$ pytest t.py -k 'no bar' -n 1
...
gw0 I
gw0 [1]

WARNING: Failed to generate report: No data to report.

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "_pytest\main.py", line 196, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "_pytest\main.py", line 246, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "pluggy\hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "pluggy\manager.py", line 87, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "pluggy\manager.py", line 81, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "pluggy\callers.py", line 203, in _multicall
INTERNALERROR>     gen.send(outcome)
INTERNALERROR>   File "pluggy\callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "pluggy\callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "xdist\dsession.py", line 115, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "xdist\dsession.py", line 138, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "xdist\dsession.py", line 180, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('t.py::test_foo', <WorkerController gw0>)
INTERNALERROR> assert not 't.py::test_foo'

============================ no tests ran in 0.60s ============================
```

**Comment by Zac-HD** [comment]
Closing as duplicate / case of #204.

**Comment by sikmir** [comment]
> Closing as duplicate / case of #204.

Why this issue is duplicate? #204 is about problem with pytest-timeout, but this issue is reproducable even without pytest-timeout.
