### ISSUE TITLE
Cannot pass object to the report (crashitem)

### ISSUE THREAD

**Issue by tetienne** [pytest-dev/pytest-xdist#552]
I have this issue only when enabling pytest-xdist (1.32.0) using the -n parameter.

After some investigation, I spot the part of our code which raise the error. In our conftest.py file we have something similar to this:
```python
    def makereport(self, item: Function, report: TestReport) -> None:
        report.foo = {"foo": object()}
```
We inject additional information within the TestReport object. 

Running a test with this will result in:

```
test_focus.py::TestFocus::test_focus[Marketplace-DISPLAY REDIRECT INTERNAL-WIDGET TOP-desktop-windows 10-chrome] 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/xdist/dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/home/tetienne/git/awesome_project/.venv/lib/python3.7/site-packages/xdist/dsession.py", line 177, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('tests/test_focus.py::TestFocus::test_focus[Marketplace-DISPLAY REDIRECT INTERNAL-WIDGET TOP-desktop-windows 10-chrome]', <WorkerController gw0>)
INTERNALERROR> assert not 'tests/test_focus.py::TestFocus::test_focus[Marketplace-DISPLAY REDIRECT INTERNAL-WIDGET TOP-desktop-windows 10-chrome]'
```

When passing a string, or an integer, there is no issue.

It's a known behavior?

**Comment by manickaraja-ponnuswami** [comment]
We have similar issue, any workaround ?

**Comment by tetienne** [comment]
The only workaround I found was to use primitive type and retrieve the information I want by another path. But it add some complexity.

**Comment by RonnyPfannschmidt** [comment]
Only execnet /json serializable objects can be used in the reports

There is a hook to handle other objects, but I'm on mobil and don't have the details at hand

**Comment by manickaraja-ponnuswami** [comment]
Great thanks for you response. @RonnyPfannschmidt when you have the time please could you point me to the hook you are talking about.

**Comment by RonnyPfannschmidt** [comment]
https://github.com/pytest-dev/pytest/blob/master/src/_pytest/hookspec.py#L515

**Comment by manickaraja-ponnuswami** [comment]
Thanks. The problem I was trying to solve was to add a url to the html report. 
I solved it using `pytest_runtest_makereport` https://pypi.org/project/pytest-html/
With this solution I could use pytest-xdist
