### ISSUE TITLE
Build failure in dependency pytest-forked (cause related to setuptools)

### ISSUE THREAD

**Issue by risoms** [pytest-dev/pytest-xdist#595]
It looks like a dependency [pytest-forked](https://github.com/pytest-dev/pytest-forked/blob/master/pyproject.toml) is causing build failures due to setuptools ~= 41.4 (console output below). This has been seen in other packages as well.

```python
 Collecting  #pytest-forked
   Downloading pytest-forked-1.3.0.tar.gz (9.8 kB)
   Installing build dependencies: started
   Installing build dependencies: finished with status 'error'
   ERROR: Command errored out with exit status 1:
    command: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hbrecn75/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i http://build.locusdev.net:10001/simple --extra-index-url https://pypi.python.org/simple --trusted-host build.locusdev.net -- 'setuptools ~= 41.4' 'setuptools_scm ~= 3.3' 'wheel ~= 0.33.6'
        cwd: None
   Complete output (20 lines):
   Looking in indexes: http://build.locusdev.net:10001/simple, https://pypi.python.org/simple/, https://pypi.python.org/simple
   Collecting setuptools~=41.4
     Downloading setuptools-41.6.0.zip (852 kB)
       ERROR: Command errored out with exit status 1:
        command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fobv7n3k/setuptools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fobv7n3k/setuptools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-fobv7n3k/setuptools/pip-egg-info
            cwd: /tmp/pip-install-fobv7n3k/setuptools/
       Complete output (9 lines):
       Traceback (most recent call last):
         File "<string>", line 1, in <module>
         File "/tmp/pip-install-fobv7n3k/setuptools/setuptools/__init__.py", line 6, in <module>
           import distutils.core
         File "/usr/local/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 83, in create_module
           return importlib.import_module('setuptools._distutils')
         File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
       ModuleNotFoundError: No module named 'setuptools._distutils'
       ----------------------------------------
   ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
   WARNING: You are using pip version 20.0.2; however, version 20.2.2 is available.
   You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
   ----------------------------------------
 ERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hbrecn75/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i http://build.locusdev.net:10001/simple --extra-index-url https://pypi.python.org/simple --trusted-host build.locusdev.net -- 'setuptools ~= 41.4' 'setuptools_scm ~= 3.3' 'wheel ~= 0.33.6' Check the logs for full command output.
 WARNING: You are using pip version 20.0.2; however, version 20.2.2 is available.
 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

Refs:
- pypa/pip#6264
- pypa/pip#8823
- pypa/setuptools#2353

**Comment by nicoddemus** [comment]
Thanks for the report, but it seems this is due to https://github.com/pypa/pip/issues/6264, so I'm closing this here. 👍
