### ISSUE TITLE
Pytest-xdist is getting crashed with pytest-timeout

### ISSUE THREAD

**Issue by ramkitr** [pytest-dev/pytest-xdist#631]
```
scheduling tests via LoadScopeScheduling

data_plane/tests/vpn/appsteering_with_loss_with_de2e/appsteering_with_loss_with_de2e_test.py::TestAppsteeringWithLossWithDE2E::test_appsteering_for_upload_traffic_on_de2e_path_with_two_lossy_links 

data_plane/tests/vpn/app_steering_with_de2e/appsteeringwithde2e_test.py::TestAppSteeringWithDE2E::test_appsteering_e2e_preferred_fixed_link_down 

data_plane/tests/vpn/configurable_ike_rekey_timers/configurable_ike_rekey_timer_gateway_path_test.py::TestConfigurableIkeRekeyTimerGatewayPath::test_E2E_flow_with_ike_timers_expiry 

data_plane/tests/vpn/configurable_ike_rekey_timers/configurable_ike_rekey_timers_for_nvs_tunnel_test.py::TestConfigureIkeRekeyTimersForNvs::test_rekey_timers_configuration_with_nvs_via_gateway 

data_plane/tests/vpn/VpnRateLimiting/vpn_rate_limiting_via_hub_test.py::TestVpnRateLimitingViaHub::test_verify_tx_and_rx_ratelimit_on_e2e_path_via_hub_for_low_priority_traffic 

data_plane/tests/vpn/VpnRateLimiting/vpn_rate_limiting_test.py::TestVpnRateLimiting::test_verify_rx_ratelimit_on_e2e_path_with_multiple_rules INTERNALERROR> Traceback (most recent call last):

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 105, in wrap_session

INTERNALERROR>     session.exitstatus = doit(config, session) or 0

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 141, in _main

INTERNALERROR>     config.hook.pytest_runtestloop(session=session)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__

INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec

INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>

INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute

INTERNALERROR>     res = hook_impl.function(*args)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/xdist/remote.py", line 65, in pytest_runtestloop

INTERNALERROR>     self.run_one_test(torun)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/xdist/remote.py", line 84, in run_one_test

INTERNALERROR>     nextitem=nextitem)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__

INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec

INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>

INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute

INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 245, in _wrapped_call

INTERNALERROR>     next(wrap_controller)   # first yield

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/pytest_timeout.py", line 73, in pytest_runtest_protocol

INTERNALERROR>     timeout_setup(item)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/pytest_timeout.py", line 106, in timeout_setup

INTERNALERROR>     signal.signal(signal.SIGALRM, handler)

INTERNALERROR>   File "/usr/lib/python3.6/signal.py", line 47, in signal

INTERNALERROR>     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))

INTERNALERROR> ValueError: signal only works in main thread



INTERNALERROR> Traceback (most recent call last):

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 105, in wrap_session

INTERNALERROR>     session.exitstatus = doit(config, session) or 0

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/main.py", line 141, in _main

INTERNALERROR>     config.hook.pytest_runtestloop(session=session)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__

INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec

INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>

INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute

INTERNALERROR>     res = hook_impl.function(*args)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/xdist/dsession.py", line 116, in pytest_runtestloop

INTERNALERROR>     self.loop_once()

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/xdist/dsession.py", line 139, in loop_once

INTERNALERROR>     call(**kwargs)

INTERNALERROR>   File "/usr/lib/python3.6/site-packages/xdist/dsession.py", line 181, in worker_workerfinished

INTERNALERROR>     assert not crashitem, (crashitem, node)

INTERNALERROR> AssertionError: ('data_plane/tests/vpn/VpnRateLimiting/vpn_rate_limiting_via_gateway_test.py::TestVpnRateLimitingViaGateway::()::test_verify_tx_and_rx_ratelimit_on_e2dc_path_for_low_priority_traffic', <WorkerController gw3>)

INTERNALERROR> assert not 'data_plane/tests/vpn/VpnRateLimiting/vpn_rate_limiting_via_gateway_test.py::TestVpnRateLimitingViaGateway::()::test_verify_tx_and_rx_ratelimit_on_e2dc_path_for_low_priority_traffic'

```

My Packages:

# Pytest and plugins
faker==1.0.7
botocore==1.17.62
pytest==3.1.2
pytest-benchmark==3.1.1
pytest-cache==1.0
pytest-cov==2.5.1
pytest-forked==1.0.2
pytest-html==1.20
pytest-helpers-namespace==2017.11.11
pytest-mock==1.10
pytest-ordering==0.5
pytest-xdist==1.22.1
pdbpp==0.9.3

**Comment by madlabman** [comment]
@ramkitr The issue fixed in `pytest-timeout==2.0.0`.

**Comment by ramkitr** [comment]
Thanks @madlabman
