### ISSUE TITLE
Internal error when a fixture raises an exception

### ISSUE THREAD

**Issue by bjones1** [pytest-dev/pytest-xdist#65]
Using the following code in [test_import.py](https://github.com/pytest-dev/pytest-xdist/files/301452/test_import.py.txt):

``` Python
import pytest

@pytest.fixture(params=['1', '2'])
def crasher():
    raise RuntimeError

def test_aaa0(crasher):
    pass
def test_aaa1(crasher):
    pass
```

Running as `py.test -n 1 --maxfail 1` produces:
```
============================= test session starts =============================
platform win32 -- Python 3.5.1, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: E:\tmp, inifile:
plugins: xdist-1.14
gw0 [4]
scheduling tests via LoadScheduling
EINTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\bjones\downloads\anaconda3\lib\site-packages\_pytest\main.py", line 94, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "c:\users\bjones\downloads\anaconda3\lib\site-packages\_pytest\main.py", line 125, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "c:\users\bjones\downloads\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "c:\users\bjones\downloads\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "c:\users\bjones\downloads\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "c:\users\bjones\downloads\anaconda3\lib\site-packages\_pytest\vendored_packages\pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "<remote exec>", line 49, in pytest_runtestloop
INTERNALERROR>   File "c:\users\bjones\downloads\anaconda3\lib\site-packages\execnet\gateway_base.py", line 737, in receive
INTERNALERROR>     raise self._getremoteerror() or EOFError()
INTERNALERROR> EOFError

=================================== ERRORS ====================================
_______________________ ERROR at setup of test_aaa0[1] ________________________
[gw0] win32 -- Python 3.5.1 c:\users\bjones\downloads\anaconda3\python.exe
@pytest.fixture(params=['1', '2'])
    def crasher():
>       raise RuntimeError
E       RuntimeError

test_import.py:5: RuntimeError
!!!!!!!!!!!! xdist.dsession.Interrupted: stopping after 1 failures !!!!!!!!!!!!
=========================== 1 error in 0.59 seconds ===========================```
```
Removing either the ``--maxfail`` or the `-n` flag avoids the INTERNALERROR.

**Comment by nicoddemus** [comment]
Thanks!

**Comment by bjones1** [comment]
Wow -- I'm very impressed. Thanks for the quick turnaround on this fix!
