### ISSUE TITLE
Only v1.34 is still compatible with Pytest 5

### ISSUE THREAD

**Issue by Apteryks** [pytest-dev/pytest-xdist#697]
I believe Pytest 5 is still widely used in various GNU/Linux distributions.

Unfortunately, I have to go all the way back to the v1.34 release of xdist to get the test suite to pass; anything newer throws an INTERNALERROR, like so:

```
starting phase `check'
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /gnu/store/f8s95qc6dfhl0r45m70hczw5zip0xjxq-python-wrapper-3.8.2/bin/python
cachedir: .pytest_cache
rootdir: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0, inifile: tox.ini, testpaths: testing
plugins: xdist-2.2.0, forked-1.3.0
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I / gw8 I / gw9 I / gw10 I / gw11 I / gw12 I / gw13 I / gw14 I / gw15 I / gw16 I / gw17 I / gw18 I / gw19 I / gw20 I / gw21 I / gw22 I / gw23 I
[gw0] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw1] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw2] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw3] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw4] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw5] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw6] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw7] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw8] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw9] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw10] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw11] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw12] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw13] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw14] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw15] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw16] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw17] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw18] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw19] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw20] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw21] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw22] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw23] linux Python 3.8.2 cwd: /tmp/guix-build-python-pytest-xdist-2.2.0.drv-0/pytest-xdist-2.2.0
[gw0] Python 3.8.2 (default, Jan  1 1970, 00:00:01)  -- [GCC 7.5.0]
[gw1] Python 3.8.2 (default, Jan  1 1970, 00:00:01)  -- [GCC 7.5.0]
[gw2] Python 3.8.2 (default, Jan  1 1970, 00:00:01)  -- [GCC 7.5.0]
[gw3] Python 3.8.2 (default, Jan  1 1970, 00:00:01)  -- [GCC 7.5.0]
[gw4] Python 3.8.2 (default, Jan  1 1970, 00:00:01)  -- [GCC 7.5.0]
[gw5] Python 3.8.2 (default, Jan  1 1970, 00:00:01)  -- [GCC 7.5.0]
[gw6] Python 3.8.2 (default, Jan  1 1970, 00:00:01)  -- [GCC 7.5.0]
INTERNALERROR> def worker_internal_error(self, node, formatted_error):
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>     
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
INTERNALERROR> E           AssertionError: Traceback (most recent call last):
INTERNALERROR> E               File "/gnu/store/0ksg9ka7k0j0yad767741x50ray8xybk-python-pytest-bootstrap-5.3.5/lib/python3.8/site-packages/_pytest/main.py", line 197, in wrap_session
INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
INTERNALERROR> E               File "/gnu/store/0ksg9ka7k0j0yad767741x50ray8xybk-python-pytest-bootstrap-5.3.5/lib/python3.8/site-packages/_pytest/main.py", line 246, in _main
INTERNALERROR> E                 config.hook.pytest_collection(session=session)
INTERNALERROR> E               File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR> E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR> E               File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> E               File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR> E                 self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR> E               File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "/gnu/store/0ksg9ka7k0j0yad767741x50ray8xybk-python-pytest-bootstrap-5.3.5/lib/python3.8/site-packages/_pytest/main.py", line 256, in pytest_collection
INTERNALERROR> E                 return session.perform_collect()
INTERNALERROR> E               File "/gnu/store/0ksg9ka7k0j0yad767741x50ray8xybk-python-pytest-bootstrap-5.3.5/lib/python3.8/site-packages/_pytest/main.py", line 459, in perform_collect
INTERNALERROR> E                 self.config.pluginmanager.check_pending()
INTERNALERROR> E               File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 274, in check_pending
INTERNALERROR> E                 raise PluginValidationError(
INTERNALERROR> E             pluggy.manager.PluginValidationError: unknown hook 'pytest_warning_recorded' in plugin <__channelexec__.WorkerInteractor object at 0x7ffff61b3d90>
INTERNALERROR> E           assert False
INTERNALERROR> 
INTERNALERROR> /gnu/store/81j04v05zq7pb9p2c8dzfxx2qm28a4aw-python-pytest-xdist-2.2.0/lib/python3.8/site-packages/xdist/dsession.py:187: AssertionError
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/gnu/store/0ksg9ka7k0j0yad767741x50ray8xybk-python-pytest-bootstrap-5.3.5/lib/python3.8/site-packages/_pytest/main.py", line 197, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/gnu/store/0ksg9ka7k0j0yad767741x50ray8xybk-python-pytest-bootstrap-5.3.5/lib/python3.8/site-packages/_pytest/main.py", line 247, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/gnu/store/nqi6xqx8h2fxldi3xbigkc24wfzzsy5j-python-pluggy-0.13.1/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/gnu/store/81j04v05zq7pb9p2c8dzfxx2qm28a4aw-python-pytest-xdist-2.2.0/lib/python3.8/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/gnu/store/81j04v05zq7pb9p2c8dzfxx2qm28a4aw-python-pytest-xdist-2.2.0/lib/python3.8/site-packages/xdist/dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/gnu/store/81j04v05zq7pb9p2c8dzfxx2qm28a4aw-python-pytest-xdist-2.2.0/lib/python3.8/site-packages/xdist/dsession.py", line 175, in worker_workerfinished
INTERNALERROR>     self._active_nodes.remove(node)
INTERNALERROR> KeyError: <WorkerController gw0>

============================ no tests ran in 1.30s =============================
```

Moving to Pytest 6 resolves the issue, but it'd be nice to have it work for Pytest 5 at least until 2.2 when support was officially dropped (IIUC) for Pytest 5.

**Comment by Apteryks** [comment]
Hi @ssbarnea !  Was this closed as "wontfix" or will there be a bug fix release made to address this?  Thanks.

**Comment by ssbarnea** [comment]
Current version of pytest is 7, not 5. This is an open source project and TBH, I really doubt anyone would work on fixing bugs in old version, we do struggle to deal with ones from latest.

Basically I closed it in order to not give, you or others, false hopes that someone else would fix it. The unwritten rule is that if you want something fixed, you have to do it yourself ;) I hope you understand.

**Comment by Apteryks** [comment]
@ssbarnea sure, I understand.  It seems there's a way in Github to close issues as "to planned", as demonstrated by @nicoddemus, so this would have avoided the question. Cheers!
