### ISSUE TITLE
Xdist is failing in github but works fine in my local

### ISSUE THREAD

**Issue by kbo001** [pytest-dev/pytest-xdist#711]
I am getting the below error everytime I try to execute the tests in parallel:

```
plugins: forked-1.3.0, rerunfailures-10.2, xdist-2.2.0, html-3.1.1, metadata-1.11.0, timeout-1.4.2
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I
gw0 [49] / gw1 [49] / gw2 [49] / gw3 [49] / gw4 [49]

INTERNALERROR> def worker_internal_error(self, node, formatted_error):
INTERNALERROR>         """
INTERNALERROR>         pytest_internalerror() was called on the worker.
INTERNALERROR>     
INTERNALERROR>         pytest_internalerror() arguments are an excinfo and an excrepr, which can't
INTERNALERROR>         be serialized, so we go with a poor man's solution of raising an exception
INTERNALERROR>         here ourselves using the formatted message.
INTERNALERROR>         """
INTERNALERROR>         self._active_nodes.remove(node)
INTERNALERROR>         try:
INTERNALERROR> >           assert False, formatted_error
INTERNALERROR> E           AssertionError: Traceback (most recent call last):
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR> E                 session.exitstatus = doit(config, session) or 0
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR> E                 config.hook.pytest_runtestloop(session=session)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR> E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR> E                 self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/xdist/remote.py", line 72, in pytest_runtestloop
INTERNALERROR> E                 self.run_one_test(torun)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/xdist/remote.py", line 89, in run_one_test
INTERNALERROR> E                 self.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR> E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR> E                 self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR> E                 return outcome.get_result()
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR> E                 raise ex[1].with_traceback(ex[2])
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR> E                 res = hook_impl.function(*args)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pytest_rerunfailures.py", line 497, in pytest_runtest_protocol
INTERNALERROR> E                 reports = runtestprotocol(item, nextitem=nextitem, log=False)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/_pytest/runner.py", line 120, in runtestprotocol
INTERNALERROR> E                 rep = call_and_report(item, "setup", log)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/_pytest/runner.py", line 217, in call_and_report
INTERNALERROR> E                 report: TestReport = hook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR> E                 return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR> E                 return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR> E                 self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR> E               File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/callers.py", line 203, in _multicall
INTERNALERROR> E                 gen.send(outcome)
INTERNALERROR> E               File "/home/runner/work/dimagi-qa/dimagi-qa/testCases/conftest.py", line 112, in pytest_runtest_makereport
INTERNALERROR> E                 screen_img = _capture_screenshot()
INTERNALERROR> E               File "/home/runner/work/dimagi-qa/dimagi-qa/testCases/conftest.py", line 121, in _capture_screenshot
INTERNALERROR> E                 return driver.get_screenshot_as_base64()
INTERNALERROR> E             AttributeError: 'NoneType' object has no attribute 'get_screenshot_as_base64'
INTERNALERROR> E           assert False
INTERNALERROR> 
INTERNALERROR> /opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/xdist/dsession.py:187: AssertionError
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/_pytest/main.py", line 323, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/xdist/dsession.py", line 112, in pytest_runtestloop
INTERNALERROR>     self.loop_once()
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/xdist/dsession.py", line 135, in loop_once
INTERNALERROR>     call(**kwargs)
INTERNALERROR>   File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/xdist/dsession.py", line 174, in worker_workerfinished
INTERNALERROR>     assert not crashitem, (crashitem, node)
INTERNALERROR> AssertionError: ('testCases/test_01_menu_visibility.py::TestMenuVisibility::test_01_reports_menu_visibility[true]', <WorkerController gw0>)
INTERNALERROR> assert not 'testCases/test_01_menu_visibility.py::TestMenuVisibility::test_01_reports_menu_visibility[true]'

============================ no tests ran in 9.06s =============================
Error: Process completed with exit code 3.
```

**Comment by nicoddemus** [comment]
Hi @kbo001, 

Here seems to be the problem:

```
INTERNALERROR> E               File "/home/runner/work/dimagi-qa/dimagi-qa/testCases/conftest.py", line 121, in _capture_screenshot
INTERNALERROR> E                 return driver.get_screenshot_as_base64()
INTERNALERROR> E             AttributeError: 'NoneType' object has no attribute 'get_screenshot_as_base64'
```

`driver` hints that this code expects a GUI to be running? You might try `pytest-xvfb` to setup a virtual frame buffer to run your tests, but you  will need to study `dimagi-qa/testCases/conftest.py` to understand what that `driver` variable is about.

Closing for now as this does not seem to be related to xdist, but feel free to ask follow up questions.

**Comment by kbo001** [comment]
@nicoddemus when I tried to execute my code without the code for capturing screenshots (i.e., pytest_runtest_makereport) the xdist worked fine.

Below is my code:
driver = None
@pytest.mark.hookwrapper
def pytest_runtest_makereport(item):
 
    pytest_html = item.config.pluginmanager.getplugin("html")
    outcome = yield
    report = outcome.get_result()
    extra = getattr(report, 'extra', [])

    if report.when == "call" or report.when == "setup": 
        xfail = hasattr(report, 'wasxfail')
        if (report.skipped and xfail) or (report.failed and not xfail):
            file_name = report.nodeid.replace("::", "_") + ".png" 
            screen_img = _capture_screenshot
            if file_name:
                html = '<div><img src="data:image/png;base64,%s" alt="screenshot" style="width:600px;height:300px;" ' \
                       'onclick="window.open(this.src)" align="right"/></div>' % screen_img
                extra.append(pytest_html.extras.html(html))
        report.extra = extra

def _capture_screenshot():
    global driver
    return driver.get_screenshot_as_base64()

And also:
@pytest.fixture(scope="class")
def init_driver(request):
    settings = load_settings()
    chrome_options = Options()
    global driver
    if os.environ.get("CI") == "true":
        chrome_options.add_argument('--no-sandbox')
        chrome_options.add_argument('disable-extensions')
        chrome_options.add_argument('--safebrowsing-disable-download-protection')
        chrome_options.add_argument('--safebrowsing-disable-extension-blacklist')
        chrome_options.add_argument('window-size=1920,1080')
        chrome_options.add_argument('--start-maximized')
        chrome_options.add_argument('--headless')
        chrome_options.add_experimental_option("prefs", {
            "download.default_directory": str(UserInputsData.download_path),
            "download.prompt_for_download": False,
            "download.directory_upgrade": True,
            "safebrowsing.enabled": True})
    else:
        chrome_options.add_argument('--safebrowsing-disable-download-protection')
        chrome_options.add_argument('--safebrowsing-disable-extension-blacklist')
        chrome_options.add_experimental_option("prefs", {
             "download.prompt_for_download": False,
            "safebrowsing.enabled": True})
    web_driver = ChromeDriverManager().install()

    driver = webdriver.Chrome(executable_path=web_driver, options=chrome_options)
    request.cls.driver = driver
    login = LoginPage(driver, settings["url"])
    login.login(settings["login_username"], settings["login_password"])
    yield driver
    driver.quit()

**Comment by kbo001** [comment]
I finally fixed it. Installed pytest-xdist[psutil] and it got executed successfully.
