### ISSUE TITLE
Cxfreeze incompatibility

### ISSUE THREAD

**Issue by c200chromebook** [pytest-dev/pytest-xdist#729]
All,

Seeing an issue using cxfreeze with a helper file with xdist.  Code is below:
Setup File:
```
from cx_Freeze import setup, Executable

build_exe_options = {"packages": ["pytest",
                                  "pluggy",
                                  "xdist",
                                  "xdist.plugin",
                                  "xdist.remote",
                                  "pytest_forked"]}

executables = [Executable('main.py')]

setup(
    name="UTTest",
    description='UT Test',
    version=6.0,
    options={"build_exe": build_exe_options},
    executables=executables)
```
Job:
```
import sys
import os
from multiprocessing import freeze_support
import pytest


if __name__ == '__main__':
    freeze_support()
    sys.exit(pytest.main(sys.argv[1:]))
```

Running:
```
main.exe -p xdist.plugin -p freeze_support -n 2
```
yields:
```
============================================================================= test session starts ==============================================================================
platform win32 -- Python 3.7.12, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: C:\Users\...\PycharmProjects\pythonProject8
plugins: forked-1.3.0
gw0 I / gw1 IERROR: usage: main.exe [options] [file_or_dir] [file_or_dir] [...]
main.exe: error: unrecognized arguments: -u
  inifile: C:\Users\...\PycharmProjects\pythonProject8\import sys;exec(eval(sys.stdin.readline()))
  rootdir: C:\Users\...\PycharmProjects\pythonProject8

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\_pytest\main.py", line 267, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\xdist\dsession.py", line 78, in pytest_sessionstart
INTERNALERROR>     nodes = self.nodemanager.setup_nodes(putevent=self.queue.put)
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\xdist\workermanage.py", line 66, in setup_nodes
INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\xdist\workermanage.py", line 66, in <listcomp>
INTERNALERROR>     return [self.setup_node(spec, putevent) for spec in self.specs]
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\xdist\workermanage.py", line 69, in setup_node
INTERNALERROR>     gw = self.group.makegateway(spec)
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\execnet\multi.py", line 134, in makegateway
INTERNALERROR>     gw = gateway_bootstrap.bootstrap(io, spec)
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\execnet\gateway_bootstrap.py", line 101, in bootstrap
INTERNALERROR>     bootstrap_import(io, spec)
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\execnet\gateway_bootstrap.py", line 35, in bootstrap_import
INTERNALERROR>     s = io.read(1)
INTERNALERROR>   File "C:\ProgramData\Anaconda3\envs\derp\lib\site-packages\execnet\gateway_base.py", line 402, in read
INTERNALERROR>     raise EOFError("expected %d bytes, got %d" % (numbytes, len(buf)))
INTERNALERROR> EOFError: expected 1 bytes, got 0

```

**Comment by nicoddemus** [comment]
Hi @c200chromebook,

Unfortunately `execnet` (which pytest-xdist uses as a backend) does not support freezing. 

There are ideas of using a different backend, but I don't think they are being worked on actively.

Closing for now, feel free to follow up with further questions.

**Comment by c200chromebook** [comment]
Ah sorry, thanks for taking a look, at least it wasn't something I was missing.

**Comment by nicoddemus** [comment]
No worries!
