### ISSUE TITLE
pytest fails on x86_64

### ISSUE THREAD

**Issue by buschmann23** [pytest-dev/pytest-xdist#747]
Running the tests on x86_64 let them fail on one test, but running fine on i586, ppc64, ppc64le, armv7l and aarch64. This is the error output on x86_64:

```
[  214s] =================================== FAILURES ===================================
[  214s] _________________ test_internal_errors_propagate_to_controller _________________
[  214s] 
[  214s] pytester = <Pytester PosixPath('/tmp/pytest-of-abuild/pytest-1/test_internal_errors_propagate_to_controller0')>
[  214s] 
[  214s]     def test_internal_errors_propagate_to_controller(pytester: pytest.Pytester) -> None:
[  214s]         pytester.makeconftest(
[  214s]             """
[  214s]             def pytest_collection_modifyitems():
[  214s]                 raise RuntimeError("Some runtime error")
[  214s]             """
[  214s]         )
[  214s]         pytester.makepyfile("def test(): pass")
[  214s]         result = pytester.runpytest("-n1")
[  214s] >       result.stdout.fnmatch_lines(["*RuntimeError: Some runtime error*"])
[  214s] E       Failed: nomatch: '*RuntimeError: Some runtime error*'
[  214s] E           and: '============================= test session starts =============================='
[  214s] E           and: 'platform linux -- Python 3.10.1, pytest-6.2.5, py-1.10.0, pluggy-1.0.0'
[  214s] E           and: 'rootdir: /tmp/pytest-of-abuild/pytest-1/test_internal_errors_propagate_to_controller0'
[  214s] E           and: 'plugins: xdist-2.5.0, forked-1.3.0'
[  214s] E           and: 'gw0 I'
[  214s] E           and: 'gw0 [1]'
[  214s] E           and: ''
[  214s] E           and: 'INTERNALERROR> Traceback (most recent call last):'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/_pytest/main.py", line 269, in wrap_session'
[  214s] E           and: 'INTERNALERROR>     session.exitstatus = doit(config, session) or 0'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/_pytest/main.py", line 323, in _main'
[  214s] E           and: 'INTERNALERROR>     config.hook.pytest_runtestloop(session=session)'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_hooks.py", line 265, in __call__'
[  214s] E           and: 'INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec'
[  214s] E           and: 'INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_manager.py", line 327, in traced_hookexec'
[  214s] E           and: 'INTERNALERROR>     return outcome.get_result()'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result'
[  214s] E           and: 'INTERNALERROR>     raise ex[1].with_traceback(ex[2])'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_result.py", line 33, in from_call'
[  214s] E           and: 'INTERNALERROR>     result = func()'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_manager.py", line 324, in <lambda>'
[  214s] E           and: 'INTERNALERROR>     lambda: oldcall(hook_name, hook_impls, kwargs, firstresult)'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 60, in _multicall'
[  214s] E           and: 'INTERNALERROR>     return outcome.get_result()'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_result.py", line 60, in get_result'
[  214s] E           and: 'INTERNALERROR>     raise ex[1].with_traceback(ex[2])'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall'
[  214s] E           and: 'INTERNALERROR>     res = hook_impl.function(*args)'
[  214s] E           and: 'INTERNALERROR>   File "/home/abuild/rpmbuild/BUILDROOT/python-pytest-xdist-2.5.0-28.1.x86_64/usr/lib/python3.10/site-packages/xdist/dsession.py", line 117, in pytest_runtestloop'
[  214s] E           and: 'INTERNALERROR>     self.loop_once()'
[  214s] E           and: 'INTERNALERROR>   File "/home/abuild/rpmbuild/BUILDROOT/python-pytest-xdist-2.5.0-28.1.x86_64/usr/lib/python3.10/site-packages/xdist/dsession.py", line 140, in loop_once'
[  214s] E           and: 'INTERNALERROR>     call(**kwargs)'
[  214s] E           and: 'INTERNALERROR>   File "/home/abuild/rpmbuild/BUILDROOT/python-pytest-xdist-2.5.0-28.1.x86_64/usr/lib/python3.10/site-packages/xdist/dsession.py", line 265, in worker_collectionfinish'
[  214s] E           and: 'INTERNALERROR>     self.sched.schedule()'
[  214s] E           and: 'INTERNALERROR>   File "/home/abuild/rpmbuild/BUILDROOT/python-pytest-xdist-2.5.0-28.1.x86_64/usr/lib/python3.10/site-packages/xdist/scheduler/load.py", line 257, in schedule'
[  214s] E           and: 'INTERNALERROR>     self._send_tests(next(nodes), 1)'
[  214s] E           and: 'INTERNALERROR>   File "/home/abuild/rpmbuild/BUILDROOT/python-pytest-xdist-2.5.0-28.1.x86_64/usr/lib/python3.10/site-packages/xdist/scheduler/load.py", line 269, in _send_tests'
[  214s] E           and: 'INTERNALERROR>     node.send_runtest_some(tests_per_node)'
[  214s] E           and: 'INTERNALERROR>   File "/home/abuild/rpmbuild/BUILDROOT/python-pytest-xdist-2.5.0-28.1.x86_64/usr/lib/python3.10/site-packages/xdist/workermanage.py", line 288, in send_runtest_some'
[  214s] E           and: 'INTERNALERROR>     self.sendcommand("runtests", indices=indices)'
[  214s] E           and: 'INTERNALERROR>   File "/home/abuild/rpmbuild/BUILDROOT/python-pytest-xdist-2.5.0-28.1.x86_64/usr/lib/python3.10/site-packages/xdist/workermanage.py", line 304, in sendcommand'
[  214s] E           and: 'INTERNALERROR>     self.channel.send((name, kwargs))'
[  214s] E           and: 'INTERNALERROR>   File "/usr/lib/python3.10/site-packages/execnet/gateway_base.py", line 728, in send'
[  214s] E           and: 'INTERNALERROR>     raise IOError("cannot send to {!r}".format(self))'
[  214s] E           and: 'INTERNALERROR> OSError: cannot send to <Channel id=1 closed>'
[  214s] E           and: ''
[  214s] E           and: '============================ no tests ran in 0.40s ============================='
[  214s] E       remains unmatched: '*RuntimeError: Some runtime error*'
```

**Comment by RonnyPfannschmidt** [comment]
at first  glance its unclear how  this happens, none of the involved code in pytest xdist/execnet is platform dependent

**Comment by buschmann23** [comment]
Another observation is, that it fails on Python 3.10.1, but not on 3.9.9.

**Comment by buschmann23** [comment]
Hm, now it runs without issues on x86_64 also with 3.10.1. Maybe something has changed in the underlying stack in my build environment (openSUSE Build Service).

**Comment by RonnyPfannschmidt** [comment]
@buschmann23 thanks for the followup, im going to presume a bugfix happened and it was a issue with the underlying python

unfortunately we currently dont have the best debugging facilities for this
