### ISSUE TITLE
Crash during test execution

### ISSUE THREAD

**Issue by jmblanc** [pytest-dev/pytest-xdist#820]
I am using pytest==6.2.2 and pytest-xdist==2.3.0
Using this command : `pytest  -r A test_samples\test_and_build_library.py --numprocesses 1 --maxfail=500 --last-failed --html=report.html --html-report=./report --self-contained-html --junitxml=pytest-junit.xml `

I obtain the successive error message : 
`08/10/22 11:56:18  INTERNALERROR> Traceback (most recent call last):
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 269, in wrap_session
08/10/22 11:56:18  INTERNALERROR>     session.exitstatus = doit(config, session) or 0
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\_pytest\main.py", line 323, in _main
08/10/22 11:56:18  INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\hooks.py", line 286, in __call__
08/10/22 11:56:18  INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
08/10/22 11:56:18  INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
08/10/22 11:56:18  INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\callers.py", line 208, in _multicall
08/10/22 11:56:18  INTERNALERROR>     return outcome.get_result()
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\callers.py", line 80, in get_result
08/10/22 11:56:18  INTERNALERROR>     raise ex[1].with_traceback(ex[2])
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\callers.py", line 187, in _multicall
08/10/22 11:56:18  INTERNALERROR>     res = hook_impl.function(*args)
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\xdist\dsession.py", line 112, in pytest_runtestloop
08/10/22 11:56:18  INTERNALERROR>     self.loop_once()
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\xdist\dsession.py", line 135, in loop_once
08/10/22 11:56:18  INTERNALERROR>     call(**kwargs)
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\xdist\dsession.py", line 167, in worker_workerfinished
08/10/22 11:56:18  INTERNALERROR>     self.config.hook.pytest_testnodedown(node=node, error=None)
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\hooks.py", line 286, in __call__
08/10/22 11:56:18  INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
08/10/22 11:56:18  INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
08/10/22 11:56:18  INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\callers.py", line 208, in _multicall
08/10/22 11:56:18  INTERNALERROR>     return outcome.get_result()
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\callers.py", line 80, in get_result
08/10/22 11:56:18  INTERNALERROR>     raise ex[1].with_traceback(ex[2])
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pluggy\callers.py", line 187, in _multicall
08/10/22 11:56:18  INTERNALERROR>     res = hook_impl.function(*args)
08/10/22 11:56:18  INTERNALERROR>   File "C:\Users\detk\AppData\Local\Programs\Python\Python39\lib\site-packages\pytest_metadata\plugin.py", line 120, in pytest_testnodedown
08/10/22 11:56:18  INTERNALERROR>     node.config._metadata.update(node.workeroutput["metadata"])
08/10/22 11:56:18  INTERNALERROR> AttributeError: 'NoneType' object has no attribute 'update'`

**Comment by RonnyPfannschmidt** [comment]
i took the liberty to make the error log readable

this is a bug in the pytest-metadata plugin
