### ISSUE TITLE
No module named 'py' error for pytest-xdist 3.0.2

### ISSUE THREAD

**Issue by xiki-tempula** [pytest-dev/pytest-xdist#833]
Hi, I noticed that my CI is failing and I'm pulling pytest-xdist 3.0.2 and I'm getting the error of

```
+ python -m pytest -rsxX --black --cov=. tests
Traceback (most recent call last):
  File "/opt/conda/envs/test/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/envs/test/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/test/lib/python3.8/site-packages/pytest.py", line 7, in <module>
    from _pytest.assertion import register_assert_rewrite
  File "/opt/conda/envs/test/lib/python3.8/site-packages/_pytest/assertion/__init__.py", line 12, in <module>
    from _pytest.assertion import rewrite
  File "/opt/conda/envs/test/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 19, in <module>
    import py
ModuleNotFoundError: No module named 'py'
```

I noticed that this is something discussed in #246. I wonder what is the recommended way of adding py.log back? Thanks.

I have attached the full pytest package version list here.
```
  + pytest                                7.2.0  py38h578d9bd_0          conda-forge/linux-64              514kB
  + pytest-black                         0.3.12  py_0                    conda-forge/noarch                  8kB
  + pytest-cov                            4.0.0  pyhd8ed1ab_0            conda-forge/noarch                 23kB
  + pytest-lazy-fixture                   0.6.3  py_0                    conda-forge/noarch                  8kB
  + pytest-parallel                       0.1.1  pyhd8ed1ab_0            conda-forge/noarch                 10kB
  + pytest-xdist                          3.0.2  pyhd8ed1ab_0            conda-forge/noarch                 31kB
```

**Comment by nicoddemus** [comment]
Hi @xiki-tempula,

Something is wrong with your environment,

```
 File "/opt/conda/envs/test/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 19, in <module>
    import py
```

As we can see, the `rewrite.py` file in `7.2.0`, around that line, is completely different:

https://github.com/pytest-dev/pytest/blob/3af3f569d5394bb1a18426b0d57a04a094800974/src/_pytest/assertion/rewrite.py#L16-L19 

And there is no `import py` in that file. 

Try executing:

```
python -m pytest --version
```

**Comment by xiki-tempula** [comment]
Thanks. This is my fault, I have a pip dependency which uninstall the conda pytest and installed an older pytest.
