### ISSUE TITLE
DeprecationWarning about rsyncdir is raised even when rsyncdir is not used

### ISSUE THREAD

**Issue by ogrisel** [pytest-dev/pytest-xdist#840]
As observed on our CI:

```python-traceback
+ eval 'python -m pytest --showlocals --durations=20 --junitxml=test-data.xml --cov-config='\''D:\a\1\s/.coveragerc'\'' --cov sklearn --cov-report= -Werror::DeprecationWarning -Werror::FutureWarning -Werror::numpy.VisibleDeprecationWarning -Wignore:tostring:DeprecationWarning -Wignore:The\ distutils:DeprecationWarning -Wignore:distutils\ Version\ classes\ are\ deprecated:DeprecationWarning -Werror::pytest.PytestUnraisableExceptionWarning -n2 --pyargs sklearn'
++ python -m pytest --showlocals --durations=20 --junitxml=test-data.xml '--cov-config=D:\a\1\s/.coveragerc' --cov sklearn --cov-report= -Werror::DeprecationWarning -Werror::FutureWarning -Werror::numpy.VisibleDeprecationWarning -Wignore:tostring:DeprecationWarning '-Wignore:The distutils:DeprecationWarning' '-Wignore:distutils Version classes are deprecated:DeprecationWarning' -Werror::pytest.PytestUnraisableExceptionWarning -n2 --pyargs sklearn
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "C:\Miniconda\envs\testvenv\lib\site-packages\_pytest\main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "C:\Miniconda\envs\testvenv\lib\site-packages\_pytest\config\__init__.py", line 1037, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "C:\Miniconda\envs\testvenv\lib\site-packages\pluggy\_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "C:\Miniconda\envs\testvenv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "C:\Miniconda\envs\testvenv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "C:\Miniconda\envs\testvenv\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "C:\Miniconda\envs\testvenv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "C:\Miniconda\envs\testvenv\lib\site-packages\xdist\plugin.py", line 214, in pytest_configure
INTERNALERROR>     config.issue_config_time_warning(warning, 2)
INTERNALERROR>   File "C:\Miniconda\envs\testvenv\lib\site-packages\_pytest\config\__init__.py", line 1394, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> DeprecationWarning: The --rsyncdir command line argument and rsyncdirs config variable are deprecated.
INTERNALERROR> The rsync feature will be removed in pytest-xdist 4.0.
```

I did a `git grep rsyncdir` in our repo and there are no occurrence of this option.

**Comment by ogrisel** [comment]
This problem is already being discussed in https://github.com/pytest-dev/pytest-xdist/issues/825#issuecomment-1292283870.

**Comment by skirpichev** [comment]
Probably, this could be closed.  See https://github.com/pytest-dev/pytest-cov/issues/557.

**Comment by sigma67** [comment]
The warning is still happening, so I don't think it can be closed

**Comment by nicoddemus** [comment]
@sigma67 according to https://github.com/pytest-dev/pytest-cov/pull/558 this seems to be solved now and release in `pytest-cov` 4.1. Make sure to update accordingly.

Closing this for now, we can reopen if needed.

**Comment by skirpichev** [comment]
@nicoddemus, please reopen: https://github.com/pytest-dev/pytest-cov/pull/558 doesn't solve the issue (which was mentioned already in the pytest-cov issue thread).

For example, if I stop filter this DeprecationWarning in the [diofant](https://github.com/diofant/diofant):
```
$ git diff
diff --git a/pyproject.toml b/pyproject.toml
index 5fb7b16417..55bc89e403 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -137,8 +137,7 @@ norecursedirs = ['build', '.eggs', '.git']
 timeout = 1000
 xfail_strict = true
 filterwarnings = ['ignore::UserWarning',
-                  'error::DeprecationWarning',
-                  'ignore:The --rsyncdir command line argument and rsyncdirs config variable are deprecated.:DeprecationWarning']
+                  'error::DeprecationWarning']
 [tool.coverage.run]
 branch = true
 omit = ['conftest.py',
$ pip list|grep pytest-cov
pytest-cov                    4.1.0
$ pytest --cov diofant diofant/tests/interactive/
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/sk/venv/dev3.11/lib/python3.11/site-packages/_pytest/main.py", line 266, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/home/sk/venv/dev3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1054, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/home/sk/venv/dev3.11/lib/python3.11/site-packages/pluggy/_hooks.py", line 452, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self._hookimpls, kwargs, False)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/sk/venv/dev3.11/lib/python3.11/site-packages/pluggy/_manager.py", line 112, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/sk/venv/dev3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 116, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/home/sk/venv/dev3.11/lib/python3.11/site-packages/pluggy/_callers.py", line 80, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/sk/venv/dev3.11/lib/python3.11/site-packages/xdist/plugin.py", line 252, in pytest_configure
INTERNALERROR>     config.issue_config_time_warning(warning, 2)
INTERNALERROR>   File "/home/sk/venv/dev3.11/lib/python3.11/site-packages/_pytest/config/__init__.py", line 1465, in issue_config_time_warning
INTERNALERROR>     warnings.warn(warning, stacklevel=stacklevel)
INTERNALERROR> DeprecationWarning: The --rsyncdir command line argument and rsyncdirs config variable are deprecated.
INTERNALERROR> The rsync feature will be removed in pytest-xdist 4.0.
```

**Comment by nicoddemus** [comment]
Hmmm but what is actionable for pytest-xdist to do? Can you elaborate?

**Comment by nicoddemus** [comment]
I mean, AFAIU it seems somebody is passing `--rsyncdir` to pytest-xdist, but pytest-xdist itself cannot do much about it other than issue the warning.

**Comment by skirpichev** [comment]
Yeah, probably you are right.  It's pytest-cov's issue (https://github.com/pytest-dev/pytest-cov/issues/557) should be reopened.
