### ISSUE TITLE
Can't run on windows?

### ISSUE THREAD

**Issue by AlexPaiva** [pytest-dev/pytest-xdist#983]
Hey,

Running on Windows 10:

`pytest.main(["-n auto",'test.py'])`

Returns:

```
Traceback (most recent call last):
  File "C:\Users\AA\Downloads\Testing\Tests\main.py", line 526, in run_pytest_thread
    pytest.main(["-n auto",'test.py'])
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 150, in main
    config = _prepareconfig(args, plugins)
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 331, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_hooks.py", line 493, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 115, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 130, in _multicall
    teardown[0].send(outcome)
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\helpconfig.py", line 104, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_result.py", line 114, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_callers.py", line 77, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 1075, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 1425, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\config\__init__.py", line 1305, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\pluggy\_manager.py", line 398, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\_pytest\assertion\rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "C:\Users\AA\AppData\Local\Programs\Python\Python310\lib\site-packages\pytest_isolate\plugin.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

fcntl being UNIX only, does this mean I can't run xdist on windows based pytest?

**Comment by AlexPaiva** [comment]
For some reason having installed pytest-isolate was causing this conflict even when their calls had nothing to do with pytest-xdist, removing it solved it. I initially was thinking it was part of your package that is why I posted here, have no idea how it got in my venv.
