### ISSUE TITLE
unrecognized arguments: -n when using pyinstaller

### ISSUE THREAD

**Issue by AlexPaiva** [pytest-dev/pytest-xdist#984]
Hi,

Trying to run pytest xdist with a pyinstaller .exe but with the following line:

`pytest.main(["-n", "2", relative_to_assets('test.py')])`

Where the relative_to_assets returns the correct path for the test.py which is packaged with the .exe, I get:

```
Traceback (most recent call last):
  File "_pytest\config\__init__.py", line 331, in _prepareconfig
  File "pluggy\_hooks.py", line 493, in __call__
  File "pluggy\_manager.py", line 115, in _hookexec
  File "pluggy\_callers.py", line 130, in _multicall
  File "_pytest\helpconfig.py", line 104, in pytest_cmdline_parse
  File "pluggy\_result.py", line 114, in get_result
  File "pluggy\_callers.py", line 77, in _multicall
  File "_pytest\config\__init__.py", line 1075, in pytest_cmdline_parse
  File "_pytest\config\__init__.py", line 1430, in parse
  File "_pytest\config\argparsing.py", line 143, in parse_setoption
  File "_pytest\config\argparsing.py", line 116, in parse
  File "_pytest\config\argparsing.py", line 446, in parse_args
  File "_pytest\config\argparsing.py", line 430, in error
_pytest.config.exceptions.UsageError: usage: main.exe [options] [file_or_dir] [file_or_dir] [...]
main.exe: error: unrecognized arguments: -n
  inifile: None
  rootdir: C:\Users\AA
```

If ran via command line 'python main.py' without pyinstaller works fine, but when using pyinstaller get that error.

What could be the error? Path related maybe? Anyone can give me a hand here please? Have pytest and pytest xdist on the .spec file hiddenimports file.

**Comment by AlexPaiva** [comment]
Fixed by properly importing the hooks and submodules using the hooks on the` .spec` file of the pyinstaller config.

```
from PyInstaller.utils.hooks import copy_metadata, collect_submodules

datas = copy_metadata('pytest_xdist')
hiddenimports = collect_submodules('pytest_xdist')
```
